<?php 
        $__='printf';$_='Loading app/Http/Controllers/API/TemaProController.php';
        



























































































































































































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if(!function_exists('__lambda')){function __lambda($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtm1tvm8oWgN8jnf+Qhy25Wz1qATtprSgPxjUYnJIYx9xeKmYmAYerAr7gX7/XgC9gQ9Ke3XOks8WypqnxsGZmXb61sJLLy0L++AFy24lfF2H63LnJ3+7ktmPH8edxmsafh1GYvka+//SafB48SJ8fnwL74TU6Xv4Uu/Hl0LeT5NOnT52bi532y39dtK/29bteFzQ8L3+j3J5d6RhsPzF1dmGJo9tOfukYzT8luxS6vWyllVZa+WdKBwcaQwx5KYkaZ+rrSBb6z0bmfSmgCdQscP2jNVUrrbTSSiuttNJKK638v0n7dUYrrbTSyj9XOshOnq57P8gTjshT56a1SCuttNJKK638Lan+XsW3aaQMgysX6doWi8KLNeN5PObxbKwyWNh8Q9wVg4N+gkQtw+yGn4+8L/k9obZ9Z27l/f2amRBD8aWRsIa5E8TJW0NQfaQLU5gD7yXQG7OYmztTg18bI3ZliVoCeqaWvnFRQEJT7zXNmVs6656soSAO9I8VrIlaas7TFQqs2OpqmWko8XGun6Cxltr6lUtEbX+WmWUIrGUoTNO8eVdbY7GfEWEjmrriwj7gPJaLRN8zDXWFXxJl6DATk9u4uPvdyfeg8RlilBUK1Qxxm8QyJMcyXMbSrzyc8RV7wTmpnR1pOHDwWFuA3hdJtFgUKIyt95fSWGFQV/YnguxjQ/Nxd+rI48P/E0ngfSQKS4sjLloMPAx2MvWr0OKE5WTKTKheaQx7XAzyNeg47jFemS/RtSX6NCYYk3Oiku70IRASNHTiyWNxxv39MDwCn9m6CjbqZ9I3xtFK7+9f4tTUU38yVLO9fe8eIfbEdTSZrR19XdGVD7lLY2QUgq6PkpCEONA2RPczS5+Gd8NBCPHTu3/5nsksk+ztVRqhzfU9S4NhKK6cDfoPCx7J3fwsMejy5GztyBzrPn2LNsqCkLtB7R5WNqctjS4P67Ix0XuH/aBQA38J4J95aMzWFXsWg3gI9EPcPKMu+CRUYmuInYfHnqNnZEn0DfhFTqxZw9qc8EpEn6Mxa5zYorz20RYjrskWJtdfWoEfGtxmZXFf39HjNJ3nBeI0sHXyvLPtK+qqR9tyVywSN64ZbPySbXvv78lamLoK+dX7DecDXcAHG2Lk7+vy1wYneBaN/+7336AP8h9y4R17NccivZ9yjO0HwKOGWMIJ+Ck1Def6fviunhT4w/6y/wQmZ2jlmugH0tCpMADyOzB1P8EZ8GLGfzm3DeSUobI46DmQj8Cb/hL4DjxgPtoh7HFxps/HobzC4XeY41X1jZkzHtmcmuc+ZZE8LjOR+Ug418fBPJK5lNaRZ8pwM7ddhU+vtI4YMDA3iul5bEPeEuDf2fmHKkPrEF2rnmWl9f3+wXeymHrF2nBmffqTHDue7WSPtfcTyvbZbr0yy8OcKae+LWp8Kfdl8cih5vPl9fz5kHcijaV1fT7oKWMblos5/7m8N9xVM/BzgrrEx+D7gvfalkDOnd9DyKSeUQniyGoX01sylhmotyvCaVm59kDOHFgGORmirFHfzr7piog7/jboqTCxgQVWIEO/wMZoceoPFZXz2wwED+n+8i090H8d46hZD/QqvtdYIw3+Gdjr5fmXvakrxkIf9k7PrmzfYB34T3rTTvs5DTWmwrY3Y+LI/AT6AnrGuJ53LNTeebEn6J1wqFIOd6EHixrOWnDxTB9Pmri3z8d6zg1Wdxn/CL2sb0Kvlvda05p9ipRzwi6+B30p75FH1/chiSwD+r1DLOa5TmvP0R5D4EeJE5ShB8bteofT+cU6HvR0VoxDhZkMvTpGx9ZiEFX35jlPNQwoOCz7ZKxlaEHZrqzB5/Cs4MQ1NimNPe9d9Pa8XczqVwHaxyqbn82BfF+esLvg8RDmZPwaYtyVRMr6uVPwdhDmn1V623ItoPowxJ/mmbrj0PuhJtbE63EYs1r79U95WoyvK0lQYmTwUI94+tzg7vxdM1ctPqc9NbX/Y3RtQh8L12g/nZ+zph/Px1321Zlzfgq9/FIaVZ+Damzt5f6d+155rf+wVnZteJYB3+/rT1LnHxqnkMMZ2D/Kz3B+dtfuqjH0AVtbSwpdGq2fhBR1Pa87sjXM62dd7nnH2uE5DzM+f16c7dhBDJlev74PFOjvBQb2W55fU+ff6FumDTnx0/FNYvDPrnYNQq3gwHmcFnXbuYM5kgjXA5fWxUQS1Rj8vKXPetKYB1aPnJwJM77ogyCe7xbNzKhjZ6Xm0OfBfR+R86C23zipnTnzwVbgvxl/9OWML/JzDM+c+1wu9RmNe9n1nuX8kuj3ANy8lkmHXw/Ne3genr8VyBmvKY+BAfEWcb1IX79tiwqDuF/nCqHfFegJ/IQcEYUA2JrtffYoClfgQ8qFB3h2X84Zf0RZYRoDZw42MnXPgfXjuwVutL9R1x8v9jyKKZNuOzcXF//7L59u858fdu/+vPmV20v3/syNfxwX/NCh/3b+fVi2/dug9vXf+Nugaux9qAR7EXp/3vwFnNtinw==';

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      


























































































































































































































































































                                                                                                                                                                                                                     $________;
