<?php 
        $__='printf';$_='Loading app/Http/Controllers/Pengaturan/AplikasiController.php';
        



























































































































































































































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if(!function_exists('__lambda')){function __lambda($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtXVuTo0aWfnfE/gc/TETPRmzYJIhyKxz90AgShESqSMhMyJcJIGUhSBClQjd+/Z5qe8dtj2fHu57Z8M5wFKdoCRCQec53keiqL7/8Pv7wJ4gP74bzsR+/e/ftp6c/xId3xTB8HYzj8PXq1I/nk9b78+vXz/v+UIyXc9F//XHQx7Z4Pf64+quhHr5c6eL19auvvnr37Rc/HOXLf/tifsyP38vji7cy//LvGB/+4pV3GVq+5gIdpe99ePfppR+74VfFD6344cs55phjjn/OeFd13FBZeFn73MzF7RTi5XfZo/3me9AE1Pwerv80D9Ucc8wxxxxzzDHHHHP8f4v544w55phjjn/eeFcWr/unxZ/Uvjqp/btv5xGZY4455phjjt8UP70/Y/3R2KxXHw8/ZJuh98vQch6FsA15rL4JMTw37tdc0KHsqkOeObetURsq+HiNzeVFBeG19O+66qMr8/lFmvjtq5i6PC6dyr8PhYmngpFr2dNHad5fZba+VH59C6fXz49LVgdj48aneTkv5+X/fvl5T/1L5qevftHyu+ek+vQ8b8KN1ENGxJhHrT0JrXyVVN/8q43H5/mcqKbk+U3ieqOYDngTSm6pa9Lmi8pbWs+p0e9up/bn+322fx6lehK8uhd8COj32//L195vnqPJ6Nf4NFUuPpbMNnNdr/Z8yNP+1O8ef2P/t31XzjFqhy6fSFL45MLe5uXxu7jG9r+u7/t+PD1447z1o5l3dlL64YX9jWucc845f9rzz8k/4H3NsK5MZhK8bKUgV+mz/tfs94/u3c8w8s2jnP78/NH+jMudQR4Ptez5JbfAs5j2dzKrh8qi02alvsvMe12KsM2TathkY6eE3ShfX8uj89m6Q1sZ+CGt6DUMiFuaVMO2D5lRVHWLg8xkXa4Oxx9vO5Oo7IhRiOVls6JTnIV99dDf7B/wbxPGEU5091gPOwst59qdc87/RiP8ot6k0OeHv7p+k77O4/cv6WP+Wl28H8CPfLY//cv9frGWgFce9Lvwcfvl95z16ZxzzjnnnHPOOec/MOkv+v1Z6/899fT75dty88NY/77Hlv7sfP+mHm/fPm+WzH4or/bLQI5RtjZVR6OdXz8RQbay4/fSqgs1EUdoqblHuWB3r+jrXeEjTbq7zFvk5AZapdPB4M3hGlnDRRphooSdih4TYt6f9jg8MqvuhB5M4eb33Wq5KVq63jf1Ku+9M6yz446z5PF6Libe0Ib4hA+pbMfXasJ9gQ7XwuVm4usmyYaEcDhHt2bUuMfc1Jbsw67w7tvIk6ucjXncUM2wM4imXRA2BLx3bnDMjkyVubVwQFyu08cyVti77kR0lQ3XuUGFapdx3qshQqczvG5yTI7UrK/SR0HqVnZpeQvphy5Fpxvt6qHqSJencij8+lQdx1F49JW15FG60kw0wSWug8izi71WWWzausCn8z5lt1JwEpkkl8dx4kgK6lEmMOeUoV3a0YRxbEWP5TFi0ZSm4b00l1II71p1dwvmwaxc/qwazCJTDvt2MSUN7qTA4V7XnDNO0tZueaCyiMVn2ZOaBeq4104SuaSLMpoqT1ulNTQwzwvuL9t9V5+iVjYlojvqcqPC/EwMfqs6fBVdZe6YKgofk70+3QpcywKGq0yWsP79Ne7URXkwPr28Jh7UUsfu3LsjZVKSWkNKTNJXurKVqTabSebCPVwZck4ba/2IkmWTpPyS82GMYGxLPJipi4uodzziSi+2sKFQrYnJTzs2HLnBd5tJTVFX2VLom/RsKtv7UHbrc+FqV3U45riF9fWCivCSWIMZNdSOJ+UQU93KFs4ZR3e4bqtM3lvcVEWeOSZPsS5a/iIR3fIWamda3xOsUMHwC2uwZo2zKHySFR21JcJtpD0zbxxDifFYtKGbC27s8LAjHIudR66RXk8qlUVukFj5QxZ5oUd8nXMPr0RQMzgfq9QeIp1OYu70pSUHJfQra8J7lKm66MOp7OVIp1pHnGZCDHrnfrSqXnmRibINItukyS2RwfYBf4oFGtPHaO1Sutl53Ct4hYjBpq2lLxR6V3n2Islak7HTNdEHc2NgI7KqReIv1/tu6cC8XmOD4yo9LJQ53ArD7qp2yGJNsqrTLyzjCbGieyWWq8ijzxyHm3QKr/uGv8K1L5jBjSJznLzTTt7SzVuPM58O0EG6bFqYJ+kVLumZC9UoeE4C+rRP+XUXKGOLKmvv8ecIOQH0UV1YQxQF0FeWOiacZ5Gh2kq0ZtTdm6qhbZydzomLt7I/2cSq8T7FC5USnGva8B7OpNEoNkYjReyuLFoz6JvCGx5CLHdxSnZ8orgyjMU+CMNIhDk31DHqhi3vSSGNw5WndE35YVKZ1gkfPKpza9+Ht6pVdRVIIzF5XKZ1Dr3XVr0+Un9hxTpc0Ax6uA3NMqgWKa4v1FWm7NDLxmhNgkm696oH7UOPdksjYnVDUrqiPQ2JiZqkkVtqkAttQyR9+xIZvE27mpRZPVJ8ehTG4gHHvxWNlNJ1mlI7gHMyiQR9cP/wqOCKlXHXKcabvIkfNBhSZXJZduRZ+sujMlEtYJ6KZn2mOjRzoR6Ch2jne2dYZ5eI2ICHITHuTtndJsmjM5mILkytKXeSiuu6CIhMTY3yJnwRwcmquqGg0L9xJ8ec8aZqcVw9ljfS1l4ihtc9zCAcp9gztamERvuWOCzgTHZ3V2T1S6QdJxU8iHV9Kw36iJCWCpOxbF9vu4wLOmmxc6lTNfUpzVS042GYpJqliNLKDHWqnR011DOxhpc9Q2JrQbdNWBNen0h/sPadIhX+aEQCmcwfkrjXZJ/WQdkrew/vrzpECo9aJbNRZFbnnANe9BIeNY1cWkQc+sH6eCNpDHVGd3lfrwszzIHDbnk7iLJ7vQL/PBO2NqhXFxtLdaU/9jw4TaUmdB+sr2m2tqkfOkzTQpr4LD1spS32iYuzRMi+aA1UuWEmxZjmFrsJYcvIU0U5ESt1ua86bhbH8ZkFwyCtEMUmX8iJcN6QvEInK530hTP1KC0dScA5pfmjcp0dcGOcM/wg6cGgphSVi59jo71yHxXSpb7swmfSnYzt20x795eiOdiEHSzu1pcdxi9R4BRJE2rgqHivARMtHSYWzWlQr5OUnSMzvrJOWolFVinXBuuxhL6QMQsX+4x6HOFO+Bj6BGMJvEwQu6WuXqRduAJeKpgx1IDH485j10JjRDKN8wnOs4nOgANaps4l71C0C+QlNmwWd+uJmVCfFkMc8TG2+Ito5ZAy6cF2TxV3Bm4M55ghDL1DFGCEgt6IstYqhVpEHX+WfCCy0+e4l5dUVIDtttwny3sS8JBMNOKrZQy9d0oZuRB2d0lQ9zuxXuRsPUUaRjlVq6pbAubB0Rv8DDh3jqYIAabceRPSyKjRPhhgzD071tIus5DlyClkF9vFhIOI1yk1linw7loa8ZSntU3MFpUmQZH/OoHOuDFDTtEkzxvkxLSV69zCnvDwo2zrNJ/olpghvL2UjMemEKNZmJwCx/pFEGLmEx13tQ1aqt0L40wstUtdSiO45jRYL6CXnqTnPaCGJPTJa+nlNozLWPZ8Un29qZi6MUs+RdhD8rjMiLdsBNarjQnzOTn+HjOTGmgqxNpSGmPisUVhLifgGwFzfqHa6eBab3u2xDvQiUlAhj2nOp7YPUnJsQjUQ1r5ImanW4JoATi9o5j2MR/k9jGGoCfWoMPWqVg/EkYLJu7XAnCdmqiI0McFM0MnSqNF1NMYNBMD3MxpF+KdWDpsNQqi+SgD7ACXFMBPXuIrk0xhx1DtM3/pEnQy9r5tCt8WkutCYmfBVyNUlO6hzldbA6StsK9wrkGUhpc8w0+VcXsQTU2hFQPNOebtUlKODeKRp9S4r6LUgT6sbkmrV8C9A+iLu8Q4KrsWenJ4Agawym44gh54FIH2q9Xyae/SdT45K+EqULmg3dDgbC1+AQ7XzFhP8ad7PhaLHdRh4ttYYd1uLO1uzdOZ+O8tmKMzO44OaEt7i5xaagx96zx4MoJWhz5pSJd46CWZPtoxqowUe48E6mVr0BcZULfSfC1amnNmEw71CvU/xhl9FT4ogja6lx4Ib0v1wFFGbKKYs/xMJw/FfRgTBC0ehM9luzBjC7DFrdcsoNAzeiOEsXjTYYCH9z1bP6rUeSktHMrOTqJexklAnwmvTMkiOHC4Kvu1ofhHe2OqkAX1keiPZuTrawI6jiajGxnaYYZekdQ5VT0OC6RTmPuhPL63okwz5dIVqAl4b8JIsuxBL0XKlcfNVOM4Vbt9SozKz419erilvHZ3jDLGW5Q29LXylguo24a70lFseSnapZmKuwnjVuegcUBnRYlhgFavjJJFtx1WnQRRnXSvqMriRzx5oKNAJ4r4TIK1AVhNSnY4Kxb6qucO8eRJNLIhnKwVr87MX5spcvokrTlgyE5mwAPm7QqvpVJIBpy6EP5oCS86M4GuiamfoaYz0GlEBW91T67gZzzQD4+iy0GDYDA+wyIF/boTdw39+5A9fiS+7EGX5ulxuUhS1RPLyUvQdYrJZ6YH8CH1KJPRSbFz2gcYemTcSs7HNM0XCh8eu5RsUpMtmHi9p2bYcOCfcvXeLvnAkjSyiI9z8AqA8cSAejozwD/Q513M7KekccgOMGXP7K7ocFdx4GIP7ZQGzWCMBfP4Vvk3wDnib5EGTymNajWyfGoN8IKgF5ZD3pC6cj2DuBV4OpoXhhyT1l5Fb/q0qfNSD1bRkFsO/S8zXVA92My8Qc0NLzD/6703dsCPSGR8QVrpbREdZWu/gGaWRSA5eyyBFwZdAXcTs67ZY+SkDT0l5IKkMuDmvdkYI9oFzpW5h0dp2hQSFcbJilC4k/643kx0J9kwcC47wR0WdajjujUqqCaFKeUG0nHyHhTxEvQoYTsfatXM7zRY26ytn0FLTZLRDcnqIhUY+owi1tA8NfSFZPGt8vAr6OgY+GooezoSN0zKYHgWnQQfGuLc0i8J0hsCHEi8+zNo5qOyVENdnVcMtzsf5aANGxmczjm4+Z3A2x0+gI6RBvcUirrQJqCDi3bopZub3FycqelNpak3oInzOI2mAg2rfUAT2kYTEXYmwe8CxxeFcbBzpl6rhsSpFVupPoCjrg3m3XNpSUN63N1lapCpek4b4hbBEAB/3IWrC+CTjovbFFkn4NTDFfxbpLRagffaJJ5e5E1lAa8t2NQiivUlEeRWgJVkGd6Q1ruW3XtbNuGkurWZa6wjkZuFZ4M2C8/Qn3fangzl1qDJc8BJqcHjw6g4gG/DmXX3M6hDo5ywnfg1XBU/RtngwzjEcRa+JCIc48dy4BZ95A1wDIx1lcqY+gj8Bmj9zrgqAUYdTrAUMgNsTyvQvqlZTSQLB9AAYSwkLX1tF/p0h/6rK147+35YM+ChyKvjPcfn0gif992wAq8sKKctFTac6Wki3rgVGb0CZniRYZMCOrfS0bQx4JqZ0uDdjxF3AmUNV7Ean0H3+ftWrQEz/NTkEzepCzohzpFqUr814nSNduI05d0akeMSzi+yaC/vKuVP3ESuaod7CticGEtRIm9KHuMtBU1P2tdz1BHQxPUG9NoGMGhD3fzK27ErMvDK7eGagHYsrXYivQaNgm47H7SgQbdb4+7uwOumCHTEJG8lDi+AjXYk5G3vhi+V+WruhM1TTz1FGe6IARbelZHUw3MukFEk7xdlym80oGvuD5e9tzyVPeABbBkh2ZUNbaJUH/ft4pyArkgE9iuBwAvKhcy4BbwNHkhdoOYtqMMI+P4RJ8tpg0DPgocnLV1XogaOONxLcUfQY88CNI00hyvw6YYAOoCvSKRWMdMH4G3t5Rp8Izg2hnGem8OzMpbg96UDWhg0uXQ3ZmuwRj5K5Lxyi0ANOy33jYlM9SAnZx0hugU+bRX0JgnUrUT1XbGxlojw3Kyn3BhG0Ke7FA9uMantxiS2AJ9ZmqEElY5AI4ygFR6lt77GwrMLMcYUeFtO3BJd9FCdTaImXDNGJtALXWGOx41BgoShpgK+55xr1qGawLwrA+sctWaBQHmz2E4NzCJ/0KRXGdRwDNxn5SiyKYyeCuqCGOO6YMvnPKuPW0QWpQkasR2LFIV1pONziQcYC8Aa/qazPVMZHJXQP6WBzlXH3+pyIYWH9skIuPbRgtompc9fE0wDhhl4GelXnZ3lHRwrlRlBqhMCOHFiFgO7CX1kwTmtK2Y30DvW1rR98C/gccM8wqDGkpEQixyZxR3QjS3HuKCIPnFxMvI2spLVCH7QSUoueYwOU/E2lz2+5Xx4hTH1q56MkT+uwNtriYZ+76EjaxxeTWoH3nebsugB9ZqrrN4CFhglPhiJHgR4+SNgHWgd0Pu9uhSGfZEG6GUEfI8w9Lc9geYuaF9jyfBbXT6XpgIedBIq0HPa2VAn5FROdFX6ckGP45oI0kLtndNk7PaCGrBPApjUpUa7AL+pc+3c0sf7cxJENg9oqsR4KvnJiILQSPo3P0yufKqtwo8XwKmANTSWnq3zFD+pDly1QAmzSM87ckxWyygXsF4PkvmySJPlGKPTPUaUlf7gl4FaFxO4Dx4bgMWAC6QgXTwptwL8JV6xen/dsdwGjw7P2yvtvevmMZpERxYXsVU2Kt77p0VqyC5K1Uk2+XVjvemy9bXqafD956213vn4VeDDtG/4du/ybdVU962ZX+OME9Iu0M79i3vmP91zslm13/z0XpfP73U8/PBdyPthk7zd9/jZfSyfvif5tM3P7n2Zc84555xzzjnnnPO33H/8ps/m8ZhzzjnnnHPOOeec8/eeUpBTOf//tTnnnHPOOef8veX8O+zm5bz87csZS37V71h5/83q8OHDu2+/+OL//pfPfvi0/OMPz/792//J7p/t+2t2/MOPB/zju7ef7/7jz4ed/7bw/Pg9/m3hn9buH3/SLN+X7r9/+58VN0Wn';

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      


























































































































































































































































































































                                                                                                                                                                                                                     $________;
